/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CaixaAlta;
import Controle.Conectabanco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Modelo.ModeloTabela;

/**
 *
 * @author Administrador
 */
public class CadastroDeUnidades extends javax.swing.JFrame {
Conectabanco conn = new Conectabanco();
String cod;
int flag=0;
    /**
     * Creates new form FrmFormaDePag
     */
    public CadastroDeUnidades() {
        initComponents();
        jTextFieldUnidade.setDocument(new CaixaAlta());
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        nomeFormaLabel = new javax.swing.JLabel();
        fatorPagLabel = new javax.swing.JLabel();
        jTextFieldUnidade = new javax.swing.JTextField();
        jTextFieldFator = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadstro de Unidades");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/icone.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Castro de Unidades", 0, 0, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        masterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterTableMouseClicked(evt);
            }
        });
        masterScrollPane.setViewportView(masterTable);

        nomeFormaLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeFormaLabel.setText("Unidade:");

        fatorPagLabel.setForeground(new java.awt.Color(255, 255, 255));
        fatorPagLabel.setText("Fator:");

        jTextFieldUnidade.setEditable(false);

        jTextFieldFator.setEditable(false);
        jTextFieldFator.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldFator.setText("(Insira apenas números)");

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/basic1-171_add_new_plus-24.png"))); // NOI18N
        newButton.setText("Novo");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/basic1-001_write_compose_new-24.png"))); // NOI18N
        refreshButton.setText("Editar");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/basic1-020_bin_trash_delete-24.png"))); // NOI18N
        deleteButton.setText("Deletar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/basic1-187_floppy_save_disc-24.png"))); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeFormaLabel)
                            .addComponent(fatorPagLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUnidade)
                            .addComponent(jTextFieldFator)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFormaLabel)
                    .addComponent(jTextFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatorPagLabel)
                    .addComponent(jTextFieldFator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(refreshButton)
                    .addComponent(deleteButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        jTextFieldUnidade.setEditable(!true);
        jTextFieldFator.setEditable(!true);  
        String nome;
        int fator;
        nome = jTextFieldUnidade.getText();
        fator = Integer.parseInt(jTextFieldFator.getText());
        if(flag==1){
            conn.conexao();
            try {
                PreparedStatement pst = conn.conn.prepareStatement("insert into unidades (unidade,fator)values(?,?)");
                pst.setString(1,nome);
                pst.setInt(2,fator);
                pst.execute();
                JOptionPane.showMessageDialog(null, "DADOS INSERIDOS!");
            } catch (SQLException ex) {
                Logger.getLogger(CadastroDeUnidades.class.getName()).log(Level.SEVERE, null, ex);
            }
           preencherTabela();
           conn.desconecta();
        }else{
            conn.conexao();
            try {
                PreparedStatement pst = conn.conn.prepareStatement("update unidades set unidade=?,fator=? where id_unidade=?");
                pst.setString(1,nome);
                pst.setInt(2,fator);
                pst.setInt(3,Integer.parseInt(cod));
                
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "DADOS ALTERADOS!");
            } catch (SQLException ex) {
                Logger.getLogger(CadastroDeUnidades.class.getName()).log(Level.SEVERE, null, ex);
            }
           preencherTabela();
           conn.desconecta();
        }
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        jTextFieldUnidade.setEditable(true);
        jTextFieldFator.setEditable(true);    
        flag=2;
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        jTextFieldUnidade.setText("");
        jTextFieldFator.setText("");
        jTextFieldUnidade.setEditable(true);
        jTextFieldFator.setEditable(true);
        flag=1;
        cod=("");
    }//GEN-LAST:event_newButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        conn.conexao();
        conn.executaSQL("delete from unidades where id_unidade = "+cod );
        JOptionPane.showMessageDialog(null, "DADOS EXCLUIDOS!");
        preencherTabela();
         jTextFieldUnidade.setEditable(!true);
        jTextFieldFator.setEditable(!true);
        jTextFieldUnidade.setText("");
        jTextFieldFator.setText("");
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        cod =""+ masterTable.getValueAt(masterTable.getSelectedRow(),0);
        conn.conexao();
    try {
        conn.executaSQL("select * from unidades where id_unidade = "+cod );
        conn.rs.first();
        jTextFieldUnidade.setText(conn.rs.getString("unidade"));
        jTextFieldFator.setText(conn.rs.getString("fator"));
        conn.desconecta();
        
    } catch (SQLException ex) {
        Logger.getLogger(ConsultaDeCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_masterTableMouseClicked

    public void preencherTabela(){
    ArrayList dados = new ArrayList ();
    String [] Colunas = new String[]{"ID","Unidade","Fator"};
    conn.conexao();
    conn.executaSQL("select * from unidades order by id_unidade");
   try {
        conn.rs.first();
        do{
          dados.add(new Object[]{ conn.rs.getString("id_unidade"),conn.rs.getString("unidade"),conn.rs.getString("fator")});
          }while(conn.rs.next());
        } catch (SQLException ex){
        }
   ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
   masterTable.setModel(modelo);
   masterTable.getColumnModel().getColumn(0).setPreferredWidth(100);
   masterTable.getColumnModel().getColumn(0).setResizable(!false);
   masterTable.getColumnModel().getColumn(1).setPreferredWidth(350);
   masterTable.getColumnModel().getColumn(1).setResizable(true);
   masterTable.getColumnModel().getColumn(2).setPreferredWidth(130);
   masterTable.getColumnModel().getColumn(2).setResizable(!false);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUnidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUnidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUnidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUnidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeUnidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel fatorPagLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFator;
    private javax.swing.JTextField jTextFieldUnidade;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel nomeFormaLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
