/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CaixaAlta;
import Controle.Conectabanco;
import Controle.ControleTelefone;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import Modelo.ModeloTabela;
import Modelo.ModeloTelefone;

/**
 *
 * @author Administrador
 */
public class CadastroDeContatos extends javax.swing.JFrame {

    ModeloTelefone mod = new ModeloTelefone();
    ControleTelefone control = new ControleTelefone();
    Conectabanco conn = new Conectabanco();

    /**
     * Creates new form FrmTelefone
     */
    public CadastroDeContatos() {
        initComponents();
        preencherTabela("select * from telefone order by nome_tel");
        try {

            MaskFormatter formtel = new MaskFormatter("(##)####-####"); //formato do telefone
            MaskFormatter formtel1 = new MaskFormatter("(##)#####-####"); //formato do telefone
            jFormattedTextFieldTel.setFormatterFactory(new DefaultFormatterFactory(formtel));
            jFormattedTextFieldTel1.setFormatterFactory(new DefaultFormatterFactory(formtel1));
            jTextFieldBusca.setDocument(new CaixaAlta());
            jTextFieldNome.setDocument(new CaixaAlta());
        } catch (ParseException ex) {
            Logger.getLogger(CadastroDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldCod = new javax.swing.JTextField();
        jFormattedTextFieldTel = new javax.swing.JFormattedTextField();
        jLabeNum = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jLabeNum1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldOBS = new javax.swing.JTextField();
        jLabeNum2 = new javax.swing.JLabel();
        jFormattedTextFieldTel1 = new javax.swing.JFormattedTextField();
        jLabeNum3 = new javax.swing.JLabel();
        jLabeNum4 = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTelefones = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldBusca = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButtonBusca = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contatos");
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/icone.png")).getImage());
        setMaximizedBounds(new java.awt.Rectangle(50, 50, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contatos", 0, 0, new java.awt.Font("Calibri Light", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("Adiciona um novo número");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Clique aqui para Salvar, e pressione em << ou >> para atualizar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setToolTipText("Clique aqui para Salvar qualquer alteração, e pressione em << ou >> para atualizar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Deleta Item selecionado");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setEnabled(false);

        jFormattedTextFieldTel.setEditable(false);

        jLabeNum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabeNum.setText("Tel. Fixo");

        jLabelCod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCod.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCod.setText("Cód.");

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabeNum1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeNum1.setForeground(new java.awt.Color(255, 255, 255));
        jLabeNum1.setText("Nome");

        jTextFieldNome.setEditable(false);

        jTextFieldOBS.setEditable(false);

        jLabeNum2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeNum2.setForeground(new java.awt.Color(255, 255, 255));
        jLabeNum2.setText("Observações");

        jFormattedTextFieldTel1.setEditable(false);

        jLabeNum3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeNum3.setForeground(new java.awt.Color(255, 255, 255));
        jLabeNum3.setText("Cel.");

        jLabeNum4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeNum4.setForeground(new java.awt.Color(255, 255, 255));
        jLabeNum4.setText("E-mail");

        jTextFieldMail.setEditable(false);

        jTableTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTelefones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTelefonesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTelefones);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancela Operação");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Buscar: (Contêm)");

        jButtonBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/search.png"))); // NOI18N
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addGap(4, 4, 4)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addGap(178, 532, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabeNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOBS))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabeNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabeNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldNome)))
                                        .addGap(171, 171, 171)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabeNum3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabeNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonCancelar))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTextFieldCod.setText("");
        jTextFieldNome.setEditable(true);
        jFormattedTextFieldTel.setEditable(true);
        jFormattedTextFieldTel1.setEditable(true);
        jTextFieldNome.setEditable(true);
        jTextFieldMail.setEditable(true);
        jTextFieldOBS.setEditable(true);
        jButtonSalvar.setEnabled(true);
        jButtonAlterar.setEnabled(!true);
        jButtonNovo.setEnabled(!true);
        jButtonCancelar.setEnabled(!false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        mod.setTel(jFormattedTextFieldTel.getText());
        mod.setTel2(jFormattedTextFieldTel1.getText());
        mod.setNome(jTextFieldNome.getText());
        mod.setMail(jTextFieldMail.getText());
        mod.setObs(jTextFieldOBS.getText());
        control.inserir(mod);
        jButtonCancelarActionPerformed(evt);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        mod.setCod(Integer.parseInt(jTextFieldCod.getText()));
        mod.setTel(jFormattedTextFieldTel.getText());
        mod.setTel2(jFormattedTextFieldTel1.getText());
        mod.setNome(jTextFieldNome.getText());
        mod.setMail(jTextFieldMail.getText());
        mod.setObs(jTextFieldOBS.getText());
        control.alterar(mod);
        jButtonCancelarActionPerformed(evt);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        switch (JOptionPane.showConfirmDialog(null, "DESEJA EXLUIR O ITEM SELECIONADO ?  ")) {
            case 0:
                mod.setCod(Integer.parseInt(jTextFieldCod.getText()));
                control.excluir(mod);
                jButtonCancelarActionPerformed(evt);
                break;
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        jFormattedTextFieldTel1.setEditable(true);
        jTextFieldNome.setEditable(true);
        jTextFieldNome.setEditable(true);
        jTextFieldMail.setEditable(true);
        jTextFieldOBS.setEditable(true);
        jFormattedTextFieldTel.setEditable(true);
        jButtonExcluir.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(!false);
        jButtonEditar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jButtonNovo.setEnabled(!false);
        jButtonSalvar.setEnabled(!true);
        jButtonAlterar.setEnabled(!true);
        jFormattedTextFieldTel.setEditable(!true);
        jFormattedTextFieldTel1.setEditable(!true);
        jTextFieldNome.setEditable(!true);
        jTextFieldMail.setEditable(!true);
        jTextFieldOBS.setText("");
        jTextFieldCod.setText("");
        jTextFieldOBS.setEditable(!true);
        jTextFieldMail.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldTel.setText("");
        jFormattedTextFieldTel1.setText("");
        preencherTabela("select * from telefone");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaActionPerformed
        mod.setBusca(jTextFieldBusca.getText());
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(!true);
        jTextFieldNome.setEditable(!false);
        jTextFieldNome.setEditable(false);
        ModeloTelefone model = control.buscaCadastro(mod);

        jTextFieldCod.setText(String.valueOf(model.getCod()));
        jFormattedTextFieldTel.setText(model.getTel());
        jFormattedTextFieldTel1.setText(model.getTel2());
        jTextFieldNome.setText(model.getNome());
        jTextFieldMail.setText(model.getMail());
        jTextFieldOBS.setText(model.getObs());
        preencherTabela("select * from telefone where nome_tel like '%" + jTextFieldBusca.getText() + "%' order by nome_tel");

    }//GEN-LAST:event_jButtonBuscaActionPerformed

    private void jTextFieldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaActionPerformed

    }//GEN-LAST:event_jTextFieldBuscaActionPerformed

    private void jTableTelefonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTelefonesMouseClicked
        jFormattedTextFieldTel.setEditable(!true);
        jFormattedTextFieldTel1.setEditable(!true);
        jTextFieldNome.setEditable(!true);
        jTextFieldMail.setEditable(!true);
        jTextFieldOBS.setEditable(!true);

        jButtonEditar.setEnabled(true);
        jButtonAlterar.setEnabled(!true);
        String nome_tel = "" + jTableTelefones.getValueAt(jTableTelefones.getSelectedRow(), 0);
        conn.conexao();
        conn.executaSQL("select * from telefone where nome_tel like '" + nome_tel + "'");
        try {
            conn.rs.first();
            jTextFieldCod.setText(String.valueOf(conn.rs.getInt("id_telefone")));
            jTextFieldNome.setText(conn.rs.getString("nome_tel"));
            jTextFieldMail.setText(conn.rs.getString("mail_tel"));
            jTextFieldOBS.setText(conn.rs.getString("obs_tel"));
            jFormattedTextFieldTel.setText(conn.rs.getString("numero_tel"));
            jFormattedTextFieldTel1.setText(conn.rs.getString("numero_tel2"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Carregar da tabela !" + ex);
        }
        conn.desconecta();

    }//GEN-LAST:event_jTableTelefonesMouseClicked
    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Nome", "Telefone", "Celular", "E-mail", "Observações"};

        conn.conexao();
        conn.executaSQL(SQL);
        try {
            conn.rs.first();
            do {
                dados.add(new Object[]{conn.rs.getString("nome_tel"), conn.rs.getString("numero_tel"), conn.rs.getString("numero_tel2"), conn.rs.getString("mail_tel"), conn.rs.getString("obs_tel")});
            } while (conn.rs.next());
        } catch (SQLException ex) {
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        jTableTelefones.setModel(modelo);
        jTableTelefones.getColumnModel().getColumn(0).setPreferredWidth(240);
        jTableTelefones.getColumnModel().getColumn(0).setResizable(false);
        jTableTelefones.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableTelefones.getColumnModel().getColumn(1).setResizable(false);
        jTableTelefones.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableTelefones.getColumnModel().getColumn(2).setResizable(false);
        jTableTelefones.getColumnModel().getColumn(3).setPreferredWidth(180);
        jTableTelefones.getColumnModel().getColumn(3).setResizable(!false);
        jTableTelefones.getColumnModel().getColumn(4).setPreferredWidth(180);
        jTableTelefones.getColumnModel().getColumn(4).setResizable(!false);

        jTableTelefones.getTableHeader().setReorderingAllowed(false);
        jTableTelefones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeContatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel1;
    private javax.swing.JLabel jLabeNum;
    private javax.swing.JLabel jLabeNum1;
    private javax.swing.JLabel jLabeNum2;
    private javax.swing.JLabel jLabeNum3;
    private javax.swing.JLabel jLabeNum4;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableTelefones;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldOBS;
    // End of variables declaration//GEN-END:variables
}
