/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conectabanco;
import Controle.ControlePagamento;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import Modelo.ModeloPagamento;
import Modelo.ModeloTabela;

/**
 *
 * @author Administrador
 */
public class ConsultaContasAPagar extends javax.swing.JFrame {
int flag,flagbusca=0;
String data ,nf,idparcela;
Conectabanco conn = new Conectabanco();
ModeloPagamento mod = new ModeloPagamento();
ControlePagamento control = new ControlePagamento();
    /**
     * Creates new form FrmContasAPagar
     */
    public ConsultaContasAPagar() {
        initComponents();
          try {
            MaskFormatter formDATA = new MaskFormatter ("##/##/####"); //formato do cnpj
           jTextFieldData.setFormatterFactory(new DefaultFormatterFactory(formDATA));
           
    
        }catch (ParseException ex){
            Logger.getLogger(ConsultaContasAPagar.class.getName()).log(Level.SEVERE, null, ex);
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldParcelasValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValorCompra = new javax.swing.JTextField();
        jButtonBuscaData = new javax.swing.JButton();
        jButtonBuscaPedido = new javax.swing.JButton();
        jButtonCnacelarBaixa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldParcela = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jButtonBaixar = new javax.swing.JButton();
        jButtonCnacelarBaixa1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldData = new javax.swing.JFormattedTextField();
        jTextFieldIDCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldForn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/icone.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contas à Pagar", 0, 0, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jLabel1.setText("Compra (Nº)");

        jTextFieldNF.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldNF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Vencimento:");

        jLabel13.setText("Valor da Parcela :");

        jTextFieldParcelasValor.setEditable(false);
        jTextFieldParcelasValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldParcelasValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasValorFocusLost(evt);
            }
        });

        jLabel2.setText("Valor da Compra:");

        jTextFieldValorCompra.setEditable(false);

        jButtonBuscaData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/search.png"))); // NOI18N
        jButtonBuscaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaDataActionPerformed(evt);
            }
        });

        jButtonBuscaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/search.png"))); // NOI18N
        jButtonBuscaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaPedidoActionPerformed(evt);
            }
        });

        jButtonCnacelarBaixa.setText("Cancelar Baixa");
        jButtonCnacelarBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCnacelarBaixaActionPerformed(evt);
            }
        });

        jLabel4.setText("Parcela :");

        jTextFieldParcela.setEditable(false);

        jLabel5.setText("Estado:");

        jTextFieldEstado.setEditable(false);

        jButtonBaixar.setText("Efetuar Baixa");
        jButtonBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaixarActionPerformed(evt);
            }
        });

        jButtonCnacelarBaixa1.setText("Sair");
        jButtonCnacelarBaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCnacelarBaixa1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/printer.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldIDCompra.setEditable(false);
        jTextFieldIDCompra.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldIDCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("NF (Nº)");

        jTextFieldForn.setEditable(false);

        jLabel7.setText("Portador do Título :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCnacelarBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCnacelarBaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldForn, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldNF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldParcelasValor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldIDCompra))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscaData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIDCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscaData, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jTextFieldParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldParcelasValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCnacelarBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCnacelarBaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        idparcela =""+ Tabela.getValueAt(Tabela.getSelectedRow(),0);
        conn.conexao();
        conn.executaSQL("select * from contas_pagar inner join compra on contas_pagar.id_compra= compra.id_compra inner join fornecedores on compra.id_fornecedor = fornecedores.id_fornecedor where id_parc_compra ="+idparcela);

        try {
            conn.rs.first();
            jTextFieldIDCompra.setText(String.valueOf(conn.rs.getInt("id_compra")));
            jTextFieldData.setText(conn.rs.getString("data"));
            jTextFieldValorCompra.setText(conn.rs.getString("valor_total"));
            jTextFieldParcelasValor.setText(conn.rs.getString("valor_parcela"));
            jTextFieldEstado.setText(conn.rs.getString("estado"));
            jTextFieldParcela.setText(String.valueOf(conn.rs.getInt("numero_parcela")));
            jTextFieldNF.setText(conn.rs.getString("nf_compra"));
            jTextFieldForn.setText(conn.rs.getString("nome_fornecedor"));
            conn.desconecta();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog (null,"Erro ao Carregar da tabela !" +ex);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaMouseClicked

    private void jTextFieldParcelasValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasValorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasValorFocusGained

    private void jTextFieldParcelasValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasValorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasValorFocusLost

    private void jButtonBuscaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaDataActionPerformed
        data= jTextFieldData.getText();
        mod.setData(data);
        control.BuscaParcelaVenc(mod);
        jTextFieldIDCompra.setText(String.valueOf(mod.getCompra()));
        jTextFieldValorCompra.setText(mod.getValor_compra());
        jTextFieldParcelasValor.setText(mod.getValor_parcela());
        jTextFieldEstado.setText(mod.getEstado());
        jTextFieldParcela.setText(String.valueOf(mod.getNumparcela()));
        jTextFieldNF.setText(String.valueOf(mod.getNf()));
        preencherTabela("select * from contas_pagar inner join compra on contas_pagar.id_compra= compra.id_compra inner join fornecedores on compra.id_fornecedor = fornecedores.id_fornecedor where data ='"+mod.getData()+"'");
        flagbusca=1;
    }//GEN-LAST:event_jButtonBuscaDataActionPerformed

    private void jButtonBuscaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaPedidoActionPerformed
        if (jTextFieldNF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO DE BUSCA !");
        }else{
            nf= jTextFieldNF.getText();
            mod.setNf(nf);
            control.BuscaParcela(mod);
            jTextFieldData.setText(mod.getData());
            jTextFieldValorCompra.setText(mod.getValor_compra());
            jTextFieldParcelasValor.setText(mod.getValor_parcela());
            jTextFieldEstado.setText(mod.getEstado());
            jTextFieldParcela.setText(String.valueOf(mod.getNumparcela()));
            preencherTabela("select * from contas_pagar inner join compra on contas_pagar.id_compra= compra.id_compra inner join fornecedores on compra.id_fornecedor = fornecedores.id_fornecedor  where nf_compra ='"+mod.getNf()+"'");
        }
flagbusca=0;
    }//GEN-LAST:event_jButtonBuscaPedidoActionPerformed

    private void jButtonCnacelarBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCnacelarBaixaActionPerformed
        flag=1;
         if (flagbusca<1){
        if (flag==1){
            conn.conexao();
            try {
                PreparedStatement pst = conn.conn.prepareStatement("update contas_pagar set estado=? where id_parc_compra=?");
                pst.setString(1,"EM ABERTO");
                pst.setInt(2, Integer.parseInt(idparcela));
                pst.execute();
                JOptionPane.showMessageDialog (null,"BAIXA CANCELADA COM SUCESSO !" );
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog (null,"ERRO AO CANCELAR BAIXA !  !" +ex);
            }
            preencherTabela("select * from contas_pagar inner join compra on contas_pagar.id_compra= compra.id_compra inner join fornecedores on compra.id_fornecedor = fornecedores.id_fornecedor where  nf_compra ='"+jTextFieldNF.getText()+"'");
            conn.desconecta();}
        else{
            flag=0;
        }}else{
           if (flag==1){
            conn.conexao();
            try {
                PreparedStatement pst = conn.conn.prepareStatement("update contas_pagar set estado=? where id_parc_compra=?");
                pst.setString(1,"EM ABERTO");
                pst.setInt(2, Integer.parseInt(idparcela));
                pst.execute();
                JOptionPane.showMessageDialog (null,"BAIXA CANCELADA COM SUCESSO !" );
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog (null,"ERRO AO CANCELAR BAIXA !  !" +ex);
            }
            preencherTabela("select * from contas_pagar inner join compra on contas_pagar.id_compra= compra.id_compra inner join fornecedores on compra.id_fornecedor = fornecedores.id_fornecedor where data ='"+mod.getData()+"'");
            conn.desconecta();}
        else{
            flag=0;
        }  
         }
        flag=0;
    }//GEN-LAST:event_jButtonCnacelarBaixaActionPerformed

    private void jButtonBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaixarActionPerformed
        flag=0;
         if (flagbusca<1){
        if (flag==0){
            conn.conexao();
            try {
                PreparedStatement pst = conn.conn.prepareStatement("update contas_pagar set estado=? where id_parc_compra=?");
                pst.setString(1,"PAGO");
                pst.setInt(2, Integer.parseInt(idparcela));
                pst.execute();
                JOptionPane.showMessageDialog (null,"BAIXA EFETUADA COM SUCESSO !" );
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog (null,"ERRO AO CANCELAR BAIXA !  !" +ex);
            }
            preencherTabela("select * from contas_pagar inner join compra on contas_pagar.id_compra= compra.id_compra inner join fornecedores on compra.id_fornecedor = fornecedores.id_fornecedor where nf_compra ='"+jTextFieldNF.getText()+"'");
            conn.desconecta();}
        else{
            flag=0;
        }}else{
        if (flag==0){
            conn.conexao();
            try {
                PreparedStatement pst = conn.conn.prepareStatement("update contas_pagar set estado=? where id_parc_compra=?");
                pst.setString(1,"PAGO");
                pst.setInt(2, Integer.parseInt(idparcela));
                pst.execute();
                JOptionPane.showMessageDialog (null,"BAIXA EFETUADA COM SUCESSO !" );
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog (null,"ERRO AO CANCELAR BAIXA !  !" +ex);
            }
            preencherTabela("select * from contas_pagar inner join compra on contas_pagar.id_compra= compra.id_compra inner join fornecedores on compra.id_fornecedor = fornecedores.id_fornecedor where data ='"+mod.getData()+"'");
            conn.desconecta();}
        else{
            flag=0;
        }
    }
        flag=0;
    }//GEN-LAST:event_jButtonBaixarActionPerformed

    private void jButtonCnacelarBaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCnacelarBaixa1ActionPerformed

        dispose();

    }//GEN-LAST:event_jButtonCnacelarBaixa1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (flag==1){
            conn.conexao();

            conn.desconecta();

        }else{
            if(flag==2){
                conn.conexao();

            }else{
                JOptionPane.showMessageDialog(rootPane,"FAÇA UMA BUSCA POR DATA OU NOME ANTES DE IMPRIMIR!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
  public void preencherTabela(String SQL){
      ArrayList dados = new ArrayList ();
    String [] Colunas = new String[]{"ID","Parcela","NF","Compra","Vencimento","Fornececdor","Valor da Parcela","Estado"};
    conn.conexao();
    conn.executaSQL(SQL);
   try {
        conn.rs.first();
        do{
          dados.add(new Object[]{conn.rs.getString("id_parc_compra"), conn.rs.getString("numero_parcela"),conn.rs.getString("nf_compra"),conn.rs.getString("id_compra"),conn.rs.getString("data"),conn.rs.getString("nome_fornecedor"),conn.rs.getString("valor_parcela"),conn.rs.getString("estado")});
          }while(conn.rs.next());
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
      ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
   Tabela.setModel(modelo);
   Tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
   Tabela.getColumnModel().getColumn(0).setResizable(!false);
   Tabela.getColumnModel().getColumn(1).setPreferredWidth(100);
   Tabela.getColumnModel().getColumn(1).setResizable(true);
   Tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
   Tabela.getColumnModel().getColumn(2).setResizable(!false);
   Tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
   Tabela.getColumnModel().getColumn(3).setResizable(!false);
   Tabela.getColumnModel().getColumn(4).setPreferredWidth(130);
   Tabela.getColumnModel().getColumn(4).setResizable(!false);
   Tabela.getColumnModel().getColumn(5).setPreferredWidth(130);
   Tabela.getColumnModel().getColumn(5).setResizable(!false);
   Tabela.getColumnModel().getColumn(6).setPreferredWidth(130);
   Tabela.getColumnModel().getColumn(6).setResizable(!false);

   Tabela.getTableHeader().setReorderingAllowed(true);
   Tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
  
   } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaContasAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaContasAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaContasAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaContasAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaContasAPagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBaixar;
    private javax.swing.JButton jButtonBuscaData;
    private javax.swing.JButton jButtonBuscaPedido;
    private javax.swing.JButton jButtonCnacelarBaixa;
    private javax.swing.JButton jButtonCnacelarBaixa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldForn;
    private javax.swing.JTextField jTextFieldIDCompra;
    private javax.swing.JTextField jTextFieldNF;
    private javax.swing.JTextField jTextFieldParcela;
    private javax.swing.JTextField jTextFieldParcelasValor;
    private javax.swing.JTextField jTextFieldValorCompra;
    // End of variables declaration//GEN-END:variables
}
