/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CaixaAlta;
import Controle.Conectabanco;
import Controle.ControleCompra;
import Controle.ControleFornecedor;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import Modelo.ModeloCompra;
import Modelo.ModeloFornecedor;
import Modelo.ModeloTabela;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import Visao.Ultilitarios.GeraParcelasCompra;
import Visao.Ultilitarios.BuscaFornecedor;
import java.awt.event.KeyEvent;
import java.io.IOException;

/**
 *
 * @author Administrador
 */
public class ModuloDeCompras extends javax.swing.JFrame {

    Conectabanco conn = new Conectabanco();
    ModeloCompra mod = new ModeloCompra();
    ModeloFornecedor modfornecedor = new ModeloFornecedor();
    ControleFornecedor control = new ControleFornecedor();
    ControleCompra controlcompra = new ControleCompra();
    BuscaFornecedor enviar;
    float preco_produto, total = 0, outroscustos = 0;
    int flagForn, flagProd, codCompra, buscarelat;

    /**
     * Creates new form FrmCompra
     */
    public ModuloDeCompras() {
        initComponents();
        preencherCombobox();
        setExtendedState(MAXIMIZED_BOTH);
        conn.conexao();
        try {
            MaskFormatter formcnpj = new MaskFormatter("##.###.###/####-##"); //formato do cnpj
            jTextFieldFornecedor.setDocument(new CaixaAlta());
            jTextFieldProduto.setDocument(new CaixaAlta());
            if (flagForn == 2) {
                jTextFieldFornecedor.setFormatterFactory(new DefaultFormatterFactory(formcnpj));
            } else {
                jTextFieldFornecedor.setText("");
            }
        } catch (ParseException ex) {
            Logger.getLogger(ModuloDeCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jFormattedTextFieldData.setText(df.format(hoje));
        jTextFieldMarkup.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldNF = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldFornecedor = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldIdFornecedor = new javax.swing.JTextField();
        jButtonBuscaFornecedor = new javax.swing.JButton();
        jButtonNovoFornecedor = new javax.swing.JButton();
        jButtonNovoProduto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextFieldProduto = new javax.swing.JTextField();
        jButtonBuscaProduto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQtdade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPrecoCompra = new javax.swing.JTextField();
        jTextFieldPrecoCompraParcial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePesquisa1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCompra = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonAddDesc = new javax.swing.JButton();
        jTextFieldMarkup = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldID1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFecha = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldParcelas = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldParcelasValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Moódulo de Entrada de Materias");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/icone.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrada de Materiais", 0, 0, new java.awt.Font("Calibri Light", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("DATA DE ENTRADA :");

        jFormattedTextFieldData.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("REGISTRO Nº:");

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextFieldCod.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldCod.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("NF:");

        jTextFieldNF.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jTextFieldNF.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldNF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNF, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("BUSCAR POR:");

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Nome");
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("CNPJ");
        jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox6MouseClicked(evt);
            }
        });
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Fornecedor :");

        jTextFieldFornecedor.setEnabled(false);
        jTextFieldFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Cadastro Nº:");

        jTextFieldIdFornecedor.setEditable(false);
        jTextFieldIdFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdFornecedorActionPerformed(evt);
            }
        });

        jButtonBuscaFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/search.png"))); // NOI18N
        jButtonBuscaFornecedor.setToolTipText("Preencha o campo e faça a busca por um Cliente");
        jButtonBuscaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox6))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdFornecedor))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox5)
                        .addComponent(jCheckBox6))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addGap(4, 4, 4)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jButtonNovoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/2 (23).png"))); // NOI18N
        jButtonNovoFornecedor.setText("Novo Fornecedor");
        jButtonNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoFornecedorActionPerformed(evt);
            }
        });

        jButtonNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/SEO_and_Internet_Marketing-21-32.png"))); // NOI18N
        jButtonNovoProduto.setText("Novo Produto");
        jButtonNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoProdutoActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNovoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonNovoFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNovoProduto))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Dados da Entrada", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Produto :");

        jCheckBox1.setText("ID");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Descrição");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Ref.");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Cód. de Barras");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jTextFieldProduto.setEnabled(false);
        jTextFieldProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoActionPerformed(evt);
            }
        });

        jButtonBuscaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/search.png"))); // NOI18N
        jButtonBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaProdutoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Quantidade Comprada");

        jTextFieldQtdade.setEnabled(false);
        jTextFieldQtdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldQtdadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQtdadeFocusLost(evt);
            }
        });
        jTextFieldQtdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQtdadeKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Custo Unitário (R$)");

        jTextFieldPrecoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoCompraActionPerformed(evt);
            }
        });
        jTextFieldPrecoCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPrecoCompraKeyPressed(evt);
            }
        });

        jTextFieldPrecoCompraParcial.setEditable(false);
        jTextFieldPrecoCompraParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoCompraParcialActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total Parcial do Item (R$)");

        jButtonAdd.setText("Vincular");
        jButtonAdd.setEnabled(false);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tabela de Pesquisa de Produtos :");

        jTablePesquisa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisa1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePesquisa1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Itens da Compra :");

        jTableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableCompra);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Valor Total (R$)");

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        jTextFieldTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        jLabel8.setText("Adicionar Outros Custos (%)");

        jButtonAddDesc.setText("Conceder");
        jButtonAddDesc.setEnabled(false);
        jButtonAddDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddDescMouseClicked(evt);
            }
        });
        jButtonAddDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDescActionPerformed(evt);
            }
        });

        jTextFieldMarkup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMarkupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMarkupFocusLost(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("ID :");

        jTextFieldID.setEditable(false);
        jTextFieldID.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldID.setEnabled(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/calculator-icon.png"))); // NOI18N
        jButton1.setToolTipText("Calculadora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("IPI (%)");

        jTextFieldID1.setEditable(false);
        jTextFieldID1.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldID1.setEnabled(false);
        jTextFieldID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Unidade de Compra");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(6, 6, 6)
                                        .addComponent(jCheckBox1)
                                        .addGap(0, 0, 0)
                                        .addComponent(jCheckBox4)
                                        .addGap(0, 0, 0)
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldMarkup, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonAddDesc))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel27))
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldPrecoCompra)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldID1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldQtdade, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldPrecoCompraParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAdd)))
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox1)
                                            .addComponent(jCheckBox4)
                                            .addComponent(jCheckBox3)
                                            .addComponent(jCheckBox2))
                                        .addGap(9, 9, 9)
                                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(4, 4, 4)
                            .addComponent(jTextFieldPrecoCompraParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel14))
                                    .addGap(26, 26, 26))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldQtdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMarkup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Itens", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jButtonFinalizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/save.png"))); // NOI18N
        jButtonFinalizar.setText("Salvar Entrada");
        jButtonFinalizar.setEnabled(false);
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/stop-48.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar Entrada");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableFecha);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Forma de Pagamento");

        jLabel12.setText("Parcelas :");

        jTextFieldParcelas.setEditable(false);
        jTextFieldParcelas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasFocusLost(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Valor por Parcela :");

        jTextFieldParcelasValor.setEditable(false);
        jTextFieldParcelasValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasValorFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldParcelasValor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldParcelasValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonFinalizar)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("Fechamento", jPanel5);

        jPanel1.add(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldQtdadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtdadeFocusGained
      
    }//GEN-LAST:event_jTextFieldQtdadeFocusGained

    private void jTextFieldQtdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtdadeFocusLost

    }//GEN-LAST:event_jTextFieldQtdadeFocusLost

    private void jTextFieldPrecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoCompraActionPerformed

    private void jTextFieldProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoActionPerformed

    private void jButtonBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaProdutoActionPerformed
       switch (flagProd) {
            case 2:
                preencherTabelaPesquisa("select * from produto inner join fornecedores on produto.id_fornecedor=fornecedores.id_fornecedor where id_produto ::text like '%" + jTextFieldProduto.getText() + "%'");
                break;
            case 3:
                preencherTabelaPesquisa("select * from produto inner join fornecedores on produto.id_fornecedor=fornecedores.id_fornecedor where referencia like '%" + jTextFieldProduto.getText() + "%'");
                break;
            case 4:
                preencherTabelaPesquisa("select * from produto inner join fornecedores on produto.id_fornecedor=fornecedores.id_fornecedor where codebar like '%" + jTextFieldProduto.getText() + "%'");
                break;
            default:
                preencherTabelaPesquisa("select * from produto inner join fornecedores on produto.id_fornecedor=fornecedores.id_fornecedor where nome_produto like '%" + jTextFieldProduto.getText() + "%'");
                break;
        }

    }//GEN-LAST:event_jButtonBuscaProdutoActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked

    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        flagProd = 2;
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jTextFieldProduto.setEnabled(true);

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        flagProd = 4;
        jCheckBox1.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jTextFieldProduto.setEnabled(true);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        flagProd = 3;
        jCheckBox2.setSelected(false);
        jCheckBox1.setSelected(false);
        jCheckBox4.setSelected(false);
        jTextFieldProduto.setEnabled(true);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        flagProd = 1;
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox1.setSelected(false);
        jTextFieldProduto.setEnabled(true);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        if (jComboBox1.getSelectedItem().equals("À VISTA") || jComboBox1.getSelectedItem().equals("DÉBITO")) {
            mod.setIdCompra(codCompra);
            mod.setNomeFornecedor(jTextFieldFornecedor.getText());
            mod.setData(jFormattedTextFieldData.getText());
            mod.setValorCompra(Float.parseFloat(jTextFieldTotal.getText()));
            mod.setNf(jTextFieldNF.getText());
            mod.setQtdParcelas(Integer.parseInt(jTextFieldParcelas.getText()));
            mod.setPagamento((String) jComboBox1.getSelectedItem());
            mod.setValorParcela(jTextFieldParcelasValor.getText());
            controlcompra.FechaCompra(mod);
            chamaespelho();
            dispose();
        } else {
            mod.setIdCompra(codCompra);
            mod.setNomeFornecedor(jTextFieldFornecedor.getText());
            mod.setData(jFormattedTextFieldData.getText());
            mod.setValorCompra(Float.parseFloat(jTextFieldTotal.getText()));
            mod.setNf(jTextFieldNF.getText());
            mod.setQtdParcelas(Integer.parseInt(jTextFieldParcelas.getText()));
            mod.setPagamento((String) jComboBox1.getSelectedItem());
            mod.setValorParcela(jTextFieldParcelasValor.getText());
            controlcompra.FechaCompra(mod);
            GeraParcelasCompra frm = new GeraParcelasCompra(codCompra);
            frm.setVisible(true);

            dispose();
        }


    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        controlcompra.cancelaCompra();
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        try {
            outroscustos = Float.parseFloat(jTextFieldMarkup.getText());
            mod.setNomeProduto(jTextFieldProduto.getText());
            mod.setIdProduto(Integer.parseInt(jTextFieldID.getText()));
            mod.setQtdItem(Integer.parseInt(jTextFieldQtdade.getText()));
            mod.setUnitario(Float.parseFloat(jTextFieldPrecoCompra.getText()));
            mod.setIdCompra(codCompra);

            controlcompra.adicionaItem(mod);

            preencherTabelaCompra("select * from produto "
                    + "inner join itens_compra_produto on produto.id_produto = itens_compra_produto.id_produto "
                    + "inner join compra on compra.id_compra = itens_compra_produto.id_compra "
                    + "where compra.id_compra ='" + jTextFieldCod.getText() + "'");
            preencherTabelaPesquisa("select * from produto");

            jTextFieldProduto.setText("");
            jTextFieldQtdade.setText("");
            jTextFieldID.setText("");
            jTextFieldPrecoCompra.setText("");
            jTextFieldPrecoCompraParcial.setText("");
            jButtonAddDesc.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            jButtonFinalizar.setEnabled(true);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar quantidade !" + ex);
        }

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTablePesquisa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisa1MouseClicked
        String id_produto = "" + jTablePesquisa1.getValueAt(jTablePesquisa1.getSelectedRow(), 0);
        conn.conexao();
        conn.executaSQL("select * from produto where id_produto ::text = '" + id_produto + "'");

        try {
            conn.rs.first();
            jTextFieldQtdade.setEnabled(true);
            jTextFieldProduto.setText(conn.rs.getString("nome_produto"));
            jTextFieldID.setText(conn.rs.getString("id_produto"));
            preco_produto = conn.rs.getFloat("preco_compra");
            jTextFieldPrecoCompra.setText(conn.rs.getString("nome_produto"));
            jTextFieldPrecoCompra.setText(String.valueOf(preco_produto));
            jTextFieldQtdade.setText("1");
            conn.desconecta();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Carregar da tabela !" + ex);

        }
    }//GEN-LAST:event_jTablePesquisa1MouseClicked

    private void jTextFieldPrecoCompraParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraParcialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoCompraParcialActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jTextFieldMarkupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMarkupFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarkupFocusGained

    private void jTextFieldMarkupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMarkupFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarkupFocusLost

    private void jButtonAddDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddDescMouseClicked
        outroscustos = (Float.parseFloat(jTextFieldMarkup.getText()) / 100);
        if (outroscustos != 0) {
            total = total + (total * outroscustos);
            jTextFieldTotal.setText(String.valueOf(total));
        } else {
            JOptionPane.showMessageDialog(null, "VALOR APLICADO É INVÁLIDO!");
        }
        jButtonAddDesc.setEnabled(false);
        jTextFieldMarkup.setEnabled(false);
        jTextFieldTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jButtonAddDescMouseClicked

    private void jButtonAddDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDescActionPerformed

    }//GEN-LAST:event_jButtonAddDescActionPerformed

    private void jButtonBuscaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaFornecedorActionPerformed
        if (flagForn == 1) {

            enviar = new BuscaFornecedor();

            enviar.enviaPesquisa(jTextFieldFornecedor.getText());

            enviar.setVisible(true);
            dispose();
        } else {
            enviar = new BuscaFornecedor();

            enviar.enviaPesquisaCNPJ(jTextFieldFornecedor.getText());

            enviar.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_jButtonBuscaFornecedorActionPerformed

    private void jTextFieldIdFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdFornecedorActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        flagForn = 2;
        jCheckBox5.setSelected(false);
        jTextFieldFornecedor.setEnabled(true);
        try {
            MaskFormatter formcnpj = new MaskFormatter("##.###.###/####-##"); //formato do cnpj
            if (flagForn == 2) {
                jTextFieldFornecedor.setFormatterFactory(new DefaultFormatterFactory(formcnpj));
            } else {
                jTextFieldFornecedor.setText("");
                jTextFieldFornecedor.setDocument(new CaixaAlta());

            }
        } catch (ParseException ex) {
            Logger.getLogger(ModuloDeCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MouseClicked

    }//GEN-LAST:event_jCheckBox6MouseClicked

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        flagForn = 1;
        jCheckBox6.setSelected(false);
        jTextFieldFornecedor.setEnabled(true);
        try {
            MaskFormatter formcnpj = new MaskFormatter("##.###.###/####-##"); //formato do cnpj
            if (flagForn == 2) {
                jTextFieldFornecedor.setFormatterFactory(new DefaultFormatterFactory(formcnpj));
            } else {
                jTextFieldFornecedor.setText("");
                jTextFieldFornecedor.setDocument(new CaixaAlta());

            }
        } catch (ParseException ex) {
            Logger.getLogger(ModuloDeCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void jTextFieldNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNFActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBox1.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));
            jTextFieldTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        preencherTabelaFechamento("select * from forma_pagamento where nome_forma='" + jComboBox1.getSelectedItem() + "'");
        conn.desconecta();


    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseExited
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBox1.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));
            jTextFieldTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento  para o frame!" + ex);
        }
        conn.desconecta();

    }//GEN-LAST:event_jComboBox1MouseExited

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBox1.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));
            jTextFieldTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }

        conn.desconecta();


    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBox1.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));
            jTextFieldTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        preencherTabelaFechamento("select * from forma_pagamento where nome_forma='" + jComboBox1.getSelectedItem() + "'");
        conn.desconecta();
    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldParcelasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasFocusGained

    private void jTextFieldParcelasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasFocusLost

    private void jTextFieldParcelasValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasValorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasValorFocusGained

    private void jTextFieldParcelasValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasValorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasValorFocusLost

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoFornecedorActionPerformed
        CadastroDeFornecedores cadastro = new CadastroDeFornecedores();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButtonNovoFornecedorActionPerformed

    private void jButtonNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoProdutoActionPerformed
        CadastroDeProdutos cadastroProd = new CadastroDeProdutos();
        cadastroProd.setVisible(true);
    }//GEN-LAST:event_jButtonNovoProdutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Runtime.getRuntime().exec("C:/Windows/System32/calc.exe");
        } catch (IOException ex) {
            System.err.println("ERRO AO CHAMAR CALCULADORA \n" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldQtdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            float subtotal;
            int qtdSolicitada = Integer.parseInt(jTextFieldQtdade.getText());
            subtotal = Float.parseFloat(jTextFieldPrecoCompra.getText()) * qtdSolicitada;
            jTextFieldPrecoCompraParcial.setText(String.valueOf(subtotal));
            jButtonAdd.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldQtdadeKeyPressed

    private void jTextFieldPrecoCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            float valorparcial;
            valorparcial = Float.parseFloat(jTextFieldPrecoCompra.getText()) * Integer.parseInt(jTextFieldQtdade.getText());
            jTextFieldPrecoCompraParcial.setText(String.valueOf(valorparcial));
        }
    }//GEN-LAST:event_jTextFieldPrecoCompraKeyPressed

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
    float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBox1.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));
            jTextFieldTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento  para o frame!" + ex);
        }
        conn.desconecta();
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jTextFieldID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID1ActionPerformed
    public void recebeDadosFornecedor(String nome_fornecedor) {
        modfornecedor.setBusca(nome_fornecedor);
        ModeloFornecedor model = control.buscaCadastro(modfornecedor);
        jTextFieldFornecedor.setText(model.getNome());
        jTextFieldIdFornecedor.setText(String.valueOf(model.getId()));

        try {
            PreparedStatement pst = conn.conn.prepareStatement("insert into compra (valor_compra,id_registro) values (?,?)");
            pst.setFloat(1, 0);
            pst.setInt(2, 1);
            pst.execute();
            conn.executaSQL("select * from compra");
            conn.rs.last();
            codCompra = conn.rs.getInt("id_compra");
            jTextFieldCod.setText(String.valueOf(codCompra));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro !" + ex);
        }

    }

    public void preencherTabelaPesquisa(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"ID", "Produto", "Referencia", "Preço de Custo", "Quantidade", "Fornecedor"};
        conn.conexao();
        conn.executaSQL(SQL);
        try {
            conn.rs.first();
            do {
                dados.add(new Object[]{conn.rs.getString("id_produto"), conn.rs.getString("nome_produto"), conn.rs.getString("referencia"), conn.rs.getString("preco_compra"), conn.rs.getString("quantidade"), conn.rs.getString("nome_fornecedor")});
            } while (conn.rs.next());
        } catch (SQLException ex) {
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        jTablePesquisa1.setModel(modelo);
        jTablePesquisa1.getColumnModel().getColumn(0).setPreferredWidth(110);
        jTablePesquisa1.getColumnModel().getColumn(0).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTablePesquisa1.getColumnModel().getColumn(1).setResizable(true);
        jTablePesquisa1.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTablePesquisa1.getColumnModel().getColumn(2).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTablePesquisa1.getColumnModel().getColumn(3).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTablePesquisa1.getColumnModel().getColumn(4).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(5).setPreferredWidth(600);
        jTablePesquisa1.getColumnModel().getColumn(5).setResizable(!false);

        jTablePesquisa1.getTableHeader().setReorderingAllowed(true);
        jTablePesquisa1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void preencherTabelaCompra(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"ID", "Produto", "Referencia", "Preço de Custo", "Quantidade", "Valor Total"};
        conn.conexao();
        conn.executaSQL(SQL);
        try {
            conn.rs.first();
            do {
                float valorProduto = conn.rs.getFloat("preco_compra");
                int qtdVendida = conn.rs.getInt("quantidade_produto");
                dados.add(new Object[]{conn.rs.getString("id_produto"), conn.rs.getString("nome_produto"), conn.rs.getString("referencia"), conn.rs.getString("preco_compra"), conn.rs.getString("quantidade_produto"), valorProduto * qtdVendida});
            } while (conn.rs.next());
        } catch (SQLException ex) {
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        jTableCompra.setModel(modelo);
        jTableCompra.getColumnModel().getColumn(0).setPreferredWidth(110);
        jTableCompra.getColumnModel().getColumn(0).setResizable(!false);
        jTableCompra.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTableCompra.getColumnModel().getColumn(1).setResizable(true);
        jTableCompra.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTableCompra.getColumnModel().getColumn(2).setResizable(!false);
        jTableCompra.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCompra.getColumnModel().getColumn(3).setResizable(!false);
        jTableCompra.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTableCompra.getColumnModel().getColumn(4).setResizable(!false);
        jTableCompra.getColumnModel().getColumn(5).setPreferredWidth(600);
        jTableCompra.getColumnModel().getColumn(5).setResizable(!false);

        jTableCompra.getTableHeader().setReorderingAllowed(true);
        jTableCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        somaproduto();
    }

    public void somaproduto() {
        total = 0;

        conn.executaSQL("select * from itens_compra_produto inner join produto on itens_compra_produto.id_produto = produto.id_produto where id_compra ='" + codCompra + "'");
        try {
            while (conn.rs.next()) {
                total = total + (conn.rs.getFloat("preco_compra") * conn.rs.getInt("quantidade_produto"));
                jTextFieldTotal.setText(String.valueOf(total));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Somar !" + ex);
        }
        conn.desconecta();
    }

    private void preencherCombobox() {
        conn.conexao();
        conn.executaSQL("select * from forma_pagamento order by id_form_pag");//conecta ao banco de dados
        jComboBox1.removeAllItems();
        try {
            //pega o primeiro dado do banco de dados como parametro
            conn.rs.first();
            do {
                jComboBox1.addItem(conn.rs.getString("nome_forma")); //adiciona os dados ao combobox
            } while (conn.rs.next());//faz o processo anterior enquanto houver proximo.
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox  :" + ex);
        }

        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento orde by id_form_pag");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            jTextFieldParcelasValor.setText(String.valueOf(totalparcela));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();

    }

    public void preencherTabelaFechamento(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Forma de Pagamento", "Parcelas", "Valor Por Parcela", "Total da Compra"};
        conn.conexao();
        float totalparcela = 0;
        conn.executaSQL(SQL);
        try {
            conn.rs.first();
            do {
                totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
                dados.add(new Object[]{conn.rs.getString("nome_forma"), conn.rs.getString("fator_pag"), totalparcela, total});
            } while (conn.rs.next());
        } catch (SQLException ex) {
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        jTableFecha.setModel(modelo);

        jTableFecha.getTableHeader().setReorderingAllowed(true);
        jTableFecha.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conn.desconecta();
    }

    public void chamaespelho() {
        conn.conexao();
        buscarelat = Integer.parseInt(jTextFieldCod.getText());
        try {
            conn.executaSQL("select * from compra\n"
                    + "inner join registro on compra.id_registro = registro.id_registro\n"
                    + "inner join fornecedores on compra.id_fornecedor=fornecedores.id_fornecedor\n"
                    + "inner join cidade on fornecedores.id_cidade = cidade.id_cidade\n"
                    + "inner join estados on cidade.id_estado = estados.id_estado\n"
                    + "inner join forma_pagamento on compra.forma=forma_pagamento.nome_forma\n"
                    + "inner join itens_compra_produto on compra.id_compra = itens_compra_produto.id_compra\n"
                    + "inner join produto on produto.id_produto = itens_compra_produto.id_produto\n"
                    + "where itens_compra_produto.id_compra =" + buscarelat);

            Map param = new HashMap();
            param.put("BUSCA", buscarelat);
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conn.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/EspelhoDeEntrada.jasper", param, relatResul);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.setExtendedState(MAXIMIZED_BOTH);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO CHAMAR RELATÓRIO  \nErro:" + ex);
        }
        conn.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloDeCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddDesc;
    private javax.swing.JButton jButtonBuscaFornecedor;
    private javax.swing.JButton jButtonBuscaProduto;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonNovoFornecedor;
    private javax.swing.JButton jButtonNovoProduto;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCompra;
    private javax.swing.JTable jTableFecha;
    private javax.swing.JTable jTablePesquisa1;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JFormattedTextField jTextFieldFornecedor;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldID1;
    private javax.swing.JTextField jTextFieldIdFornecedor;
    private javax.swing.JTextField jTextFieldMarkup;
    private javax.swing.JTextField jTextFieldNF;
    private javax.swing.JTextField jTextFieldParcelas;
    private javax.swing.JTextField jTextFieldParcelasValor;
    private javax.swing.JTextField jTextFieldPrecoCompra;
    private javax.swing.JTextField jTextFieldPrecoCompraParcial;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQtdade;
    private javax.swing.JFormattedTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
