/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CaixaAlta;
import Controle.Conectabanco;
import Controle.ControleClientes;
import Controle.ControleVenda;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import Modelo.ModeloClientes;
import Modelo.ModeloTabela;
import Modelo.ModeloVenda;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import Visao.Ultilitarios.BuscaCliente;
import Visao.Ultilitarios.GeraParcelasVenda;

/**
 *
 * @author Administrador
 */
public class ModuloDeVendas extends javax.swing.JFrame {

    Conectabanco conn = new Conectabanco();
    ModeloVenda mod = new ModeloVenda();
    ModeloClientes modCli = new ModeloClientes();
    ControleClientes control = new ControleClientes();
    ControleVenda controlVenda = new ControleVenda();
    BuscaCliente enviarBuscaCliente;

    float precoProduto, total = 0, desconto = 0;
    int flagCliente, flagProduto, codVenda, testaQuantidade, buscaRelat;

    /**
     * Creates new form Modulo_de_vendas
     */
    public ModuloDeVendas() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        preencherCombobox();

        conn.conexao();
        try {
            MaskFormatter formcnpj = new MaskFormatter("##.###.###/####-##"); //formato do cnpj
            jTextFieldCliente.setDocument(new CaixaAlta());
            jTextFieldProduto.setDocument(new CaixaAlta());
            if (2 != flagCliente) {
                jTextFieldCliente.setText("");
            } else {
                jTextFieldCliente.setFormatterFactory(new DefaultFormatterFactory(formcnpj));
            }
        } catch (ParseException ex) {
            Logger.getLogger(ModuloDeVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jFormattedTextFieldData.setText(df.format(hoje));
        jTextFieldMarkup.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVenda = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePesquisa1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMarkup = new javax.swing.JTextField();
        jButtonDesconto = new javax.swing.JButton();
        jComboBoxFormaDePag = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldParcelas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldParcelasValor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jButtonBuscaProduto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JFormattedTextField();
        jButtonBuscaCliente = new javax.swing.JButton();
        jTextFieldClienteID = new javax.swing.JTextField();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jRadioButtonCnpj = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        jTextFieldQtdade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPrecoVendaParcial = new javax.swing.JTextField();
        jButtonAddProduto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldCod = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabelProdutoSelecionado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Módulo de Vendas");
        setFocusCycleRoot(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/icone.png")).getImage());
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas", 0, 0, new java.awt.Font("Calibri Light", 0, 36))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Valor Total (R$)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Resultado da Busca:");

        jFormattedTextFieldData.setForeground(new java.awt.Color(0, 51, 255));
        jFormattedTextFieldData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableVenda);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Itens da Venda :");

        jButtonFinalizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/ven.png"))); // NOI18N
        jButtonFinalizar.setText("Finalizar Venda");
        jButtonFinalizar.setEnabled(false);
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/fg.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar Venda");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTablePesquisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisa1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePesquisa1);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Venda:");

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTotalFocusLost(evt);
            }
        });
        jTextFieldTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldTotalMouseClicked(evt);
            }
        });
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        jLabel8.setText("Desconto (%)");

        jTextFieldMarkup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMarkupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMarkupFocusLost(evt);
            }
        });

        jButtonDesconto.setText("Conceder");
        jButtonDesconto.setEnabled(false);
        jButtonDesconto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDescontoMouseClicked(evt);
            }
        });
        jButtonDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescontoActionPerformed(evt);
            }
        });

        jComboBoxFormaDePag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFormaDePag.setEnabled(false);
        jComboBoxFormaDePag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxFormaDePagFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxFormaDePagFocusLost(evt);
            }
        });
        jComboBoxFormaDePag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxFormaDePagMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxFormaDePagMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxFormaDePagMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxFormaDePagMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxFormaDePagMouseReleased(evt);
            }
        });
        jComboBoxFormaDePag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormaDePagActionPerformed(evt);
            }
        });

        jLabel11.setText("Forma de Pagamento");

        jLabel12.setText("Parcelas :");

        jTextFieldParcelas.setEditable(false);
        jTextFieldParcelas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasFocusLost(evt);
            }
        });

        jLabel13.setText("Valor por Parcela :");

        jTextFieldParcelasValor.setEditable(false);
        jTextFieldParcelasValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasValorFocusLost(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setBackground(new java.awt.Color(153, 153, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("BUSCAR POR: ");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("ID");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Descrição");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Ref.");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Cód. de Barras");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Produto :");

        jTextFieldProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoActionPerformed(evt);
            }
        });

        jButtonBuscaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/search.png"))); // NOI18N
        jButtonBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Cliente :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("BUSCAR POR:");

        jTextFieldCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteActionPerformed(evt);
            }
        });

        jButtonBuscaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/search.png"))); // NOI18N
        jButtonBuscaCliente.setToolTipText("Preencha o campo e faça a busca por um Cliente");
        jButtonBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaClienteActionPerformed(evt);
            }
        });

        jTextFieldClienteID.setEditable(false);
        jTextFieldClienteID.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteIDActionPerformed(evt);
            }
        });

        jRadioButtonNome.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonNome.setText("Nome");
        jRadioButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNomeActionPerformed(evt);
            }
        });

        jRadioButtonCnpj.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonCnpj.setText("CNPJ");
        jRadioButtonCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldClienteID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonCnpj))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonNome)
                    .addComponent(jRadioButtonCnpj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("ID");

        jTextFieldID.setEditable(false);
        jTextFieldID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldID.setForeground(new java.awt.Color(0, 0, 255));
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUANTIDADE");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VALOR UNITÁRIO (R$)");

        jTextFieldPrecoVenda.setEditable(false);
        jTextFieldPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPrecoVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoVendaActionPerformed(evt);
            }
        });

        jTextFieldQtdade.setEditable(false);
        jTextFieldQtdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldQtdade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldQtdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldQtdadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQtdadeFocusLost(evt);
            }
        });
        jTextFieldQtdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtdadeActionPerformed(evt);
            }
        });
        jTextFieldQtdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQtdadeKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("TOTAL PARCIAL DO ITEM (R$)");

        jTextFieldPrecoVendaParcial.setEditable(false);
        jTextFieldPrecoVendaParcial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPrecoVendaParcial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecoVendaParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoVendaParcialActionPerformed(evt);
            }
        });

        jButtonAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/add.png"))); // NOI18N
        jButtonAddProduto.setText("Adicionar à Venda");
        jButtonAddProduto.setEnabled(false);
        jButtonAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(jTextFieldQtdade))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecoVendaParcial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldQtdade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrecoVendaParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextFieldCod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCod.setForeground(new java.awt.Color(0, 51, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Data:");

        jLabelProdutoSelecionado.setEditable(false);
        jLabelProdutoSelecionado.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelProdutoSelecionado.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jLabelProdutoSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelProdutoSelecionadoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/calculator-icon.png"))); // NOI18N
        jButton1.setToolTipText("Calculadora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldMarkup, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFormaDePag, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldParcelasValor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addGap(21, 21, 21))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(jScrollPane3))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProdutoSelecionado)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelProdutoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8))
                            .addComponent(jTextFieldMarkup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxFormaDePag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldParcelasValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaClienteActionPerformed
        if (flagCliente == 1) {
            enviarBuscaCliente = new BuscaCliente();
            enviarBuscaCliente.enviaPesquisa(jTextFieldCliente.getText());
            enviarBuscaCliente.setVisible(true);
            dispose();
        } else {
            enviarBuscaCliente = new BuscaCliente();
            enviarBuscaCliente.enviaPesquisaCNPJ(jTextFieldCliente.getText());
            enviarBuscaCliente.setVisible(true);
            dispose();

        }


    }//GEN-LAST:event_jButtonBuscaClienteActionPerformed
    public void recebeDadosCliente(String nome_cliente) {
        modCli.setBusca(nome_cliente);
        ModeloClientes model;
        model = control.buscaCadastro(modCli);
        jTextFieldCliente.setText(model.getNome());
        jTextFieldClienteID.setText(String.valueOf(model.getId()));

        try {
            PreparedStatement pst = conn.conn.prepareStatement("insert into venda (valor_venda,id_registro) values (?,?)");
            pst.setFloat(1, 0);
            pst.setInt(2, 1);
            pst.execute();
            conn.executaSQL("select * from venda");
            conn.rs.last();
            codVenda = conn.rs.getInt("id_venda");
            jTextFieldCod.setText(String.valueOf(codVenda));
            jRadioButtonNome.setEnabled(false);
            jRadioButtonCnpj.setEnabled(false);
            jTextFieldCliente.setEnabled(false);
            jButtonBuscaCliente.setEnabled(false);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO RECEBER DADOS !" + ex);
        }

    }


    private void jTextFieldProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoActionPerformed

    }//GEN-LAST:event_jTextFieldProdutoActionPerformed

    private void jButtonBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaProdutoActionPerformed

        switch (flagProduto) {
            case 2:
                preencherTabelaPesquisa("select * from produto inner join fornecedores "
                        + "on produto.id_fornecedor=fornecedores.id_fornecedor "
                        + "inner join unidades on produto.id_unidade=unidades.id_unidade "
                        + "where id_produto ::text like '%" + jTextFieldProduto.getText() + "%' order by id_produto ");
                break;
            case 3:
                preencherTabelaPesquisa("select * from produto inner join fornecedores "
                        + "on produto.id_fornecedor=fornecedores.id_fornecedor "
                        + "inner join unidades on produto.id_unidade=unidades.id_unidade "
                        + "where referencia like '%" + jTextFieldProduto.getText() + "%' order by id_produto");
                break;
            case 4:
                preencherTabelaPesquisa("select * from produto inner join fornecedores"
                        + "on produto.id_fornecedor=fornecedores.id_fornecedor "
                        + "inner join unidades on produto.id_unidade=unidades.id_unidade "
                        + "where codebar like '%" + jTextFieldProduto.getText() + "%' order by id_produto");
                break;
            default:
                preencherTabelaPesquisa("select * from produto inner join fornecedores "
                        + "on produto.id_fornecedor=fornecedores.id_fornecedor "
                        + "inner join unidades on produto.id_unidade=unidades.id_unidade "
                        + "where nome_produto like '%" + jTextFieldProduto.getText() + "%' order by id_produto");
                break;
        }


    }//GEN-LAST:event_jButtonBuscaProdutoActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked

    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jTextFieldPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoVendaActionPerformed

    private void jButtonAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProdutoActionPerformed

        try {
            desconto = Float.parseFloat(jTextFieldMarkup.getText());
            mod.setNomeProduto(jTextFieldProduto.getText());
            mod.setIdProduto(Integer.parseInt(jTextFieldID.getText()));
            mod.setQtdItem(Integer.parseInt(jTextFieldQtdade.getText()));
            mod.setIdVenda(codVenda);
            controlVenda.adicionaItem(mod);

            preencherTabelaVenda("select * from produto "
                    + "inner join itens_venda_produto on produto.id_produto = itens_venda_produto.id_produto"
                    + " inner join venda on venda.id_venda = itens_venda_produto.id_venda "
                    + "where venda.id_venda ='" + jTextFieldCod.getText() + "'");
            preencherTabelaPesquisa("");

            jTextFieldProduto.setText("");
            jTextFieldID.setText("");
            jTextFieldQtdade.setText("");
            jTextFieldPrecoVenda.setText("");
            jTextFieldPrecoVendaParcial.setText("");
            jButtonDesconto.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            jButtonAddProduto.setEnabled(!true);
            jComboBoxFormaDePag.setEnabled(true);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO ADICIONAR PRODUTO A VENDA ! \n" + ex);
        }


    }//GEN-LAST:event_jButtonAddProdutoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        switch (JOptionPane.showConfirmDialog(null, "DESEJA CANCELAR A VENDA ? \n (A NUMERAÇÃO DA VENDA SERÁ INUTILIZADA)")) {
            case 0:
                controlVenda.cancelaVenda();
                dispose();
                ModuloDeVendas venda = new ModuloDeVendas();
                venda.setVisible(true);
                break;
            case 1:
                System.out.println("botao no clicado");
                break;
            case 2:
                System.out.println("botao cancel clicado");
                break;
        }

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldClienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteIDActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        flagProduto = 2;
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jTextFieldProduto.setEditable(true);

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        flagProduto = 1;
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox1.setSelected(false);
        jTextFieldProduto.setEditable(true);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        flagProduto = 3;
        jCheckBox2.setSelected(false);
        jCheckBox1.setSelected(false);
        jCheckBox4.setSelected(false);
        jTextFieldProduto.setEditable(true);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        flagProduto = 4;
        jCheckBox1.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jTextFieldProduto.setEditable(true);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jTablePesquisa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisa1MouseClicked
        String id_produto = "" + jTablePesquisa1.getValueAt(jTablePesquisa1.getSelectedRow(), 0);
        conn.conexao();
        conn.executaSQL("select * from produto where id_produto ::text = '" + id_produto + "'");

        try {
            conn.rs.first();
            jTextFieldQtdade.setEditable(true);
            jLabelProdutoSelecionado.setText(conn.rs.getString("nome_produto"));
            jTextFieldID.setText(conn.rs.getString("id_produto"));
            precoProduto = conn.rs.getFloat("preco_venda");
            jTextFieldPrecoVenda.setText(conn.rs.getString("nome_produto"));
            jTextFieldPrecoVenda.setText(String.valueOf(precoProduto));
            jTextFieldQtdade.setText("1");
            jTextFieldPrecoVendaParcial.setText("");
            jButtonAddProduto.setEnabled(false);
            testaQuantidade = conn.rs.getInt("quantidade"); // VAI PEGAR A QUANTIDADE TOTAL DO PRODUTO SELECIONADO, PRA COMPARAR ASSIM QUE O USUARIO DIGIRAR A QUANTIDADE SOLICITADA E DER ENTER

            conn.desconecta();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Carregar da tabela !" + ex);

        }
    }//GEN-LAST:event_jTablePesquisa1MouseClicked

    private void jTextFieldQtdadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtdadeFocusGained

    }//GEN-LAST:event_jTextFieldQtdadeFocusGained

    private void jTextFieldPrecoVendaParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoVendaParcialActionPerformed

    }//GEN-LAST:event_jTextFieldPrecoVendaParcialActionPerformed

    private void jTextFieldQtdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtdadeFocusLost

    }//GEN-LAST:event_jTextFieldQtdadeFocusLost

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed

    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        if (jComboBoxFormaDePag.getSelectedItem().equals("À VISTA") || jComboBoxFormaDePag.getSelectedItem().equals("DÉBITO")) {
            mod.setIdVenda(codVenda);
            mod.setNomeCliente(jTextFieldCliente.getText());
            mod.setData(jFormattedTextFieldData.getText());
            mod.setValorVenda(jTextFieldTotal.getText());
            mod.setQtdParcelas(Integer.parseInt(jTextFieldParcelas.getText()));
            mod.setPagamento((String) jComboBoxFormaDePag.getSelectedItem());
            mod.setValorParcela(jTextFieldParcelasValor.getText());
            controlVenda.Fechavenda(mod);
            chamapedido();

        } else {
            mod.setIdVenda(codVenda);
            mod.setNomeCliente(jTextFieldCliente.getText());
            mod.setData(jFormattedTextFieldData.getText());
            mod.setValorVenda(jTextFieldTotal.getText());
            mod.setQtdParcelas(Integer.parseInt(jTextFieldParcelas.getText()));
            mod.setPagamento((String) jComboBoxFormaDePag.getSelectedItem());
            mod.setValorParcela(jTextFieldParcelasValor.getText());
            controlVenda.Fechavenda(mod);
            GeraParcelasVenda frm = new GeraParcelasVenda(codVenda);
            frm.setVisible(true);

        }

        dispose();
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jTextFieldMarkupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMarkupFocusGained

    }//GEN-LAST:event_jTextFieldMarkupFocusGained

    private void jTextFieldMarkupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMarkupFocusLost

    }//GEN-LAST:event_jTextFieldMarkupFocusLost

    private void jButtonDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescontoActionPerformed
        int compara = Integer.parseInt(jTextFieldMarkup.getText());
        desconto = (Float.parseFloat(jTextFieldMarkup.getText()) / 100);
        if (compara >= 1) {
            total = total - (total * desconto);
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldTotal.setText(fm.format(total));
            jButtonDesconto.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO CONCEDER DESCONTO !\n(O Desconto não pode ser igual ou inferior a zero!)");

        }
    }//GEN-LAST:event_jButtonDescontoActionPerformed

    private void jButtonDescontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDescontoMouseClicked
        jButtonDesconto.setEnabled(false);
        jTextFieldMarkup.setEditable(false);
    }//GEN-LAST:event_jButtonDescontoMouseClicked

    private void jTextFieldParcelasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasFocusGained

    private void jTextFieldParcelasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasFocusLost

    private void jTextFieldParcelasValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasValorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasValorFocusGained

    private void jTextFieldParcelasValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasValorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasValorFocusLost

    private void jComboBoxFormaDePagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormaDePagActionPerformed

    }//GEN-LAST:event_jComboBoxFormaDePagActionPerformed

    private void jComboBoxFormaDePagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFormaDePagMouseClicked
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBoxFormaDePag.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));
            if (totalparcela <= 0) {
                jButtonFinalizar.setEnabled(!true);
            } else {
                jButtonFinalizar.setEnabled(true);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();

    }//GEN-LAST:event_jComboBoxFormaDePagMouseClicked

    private void jComboBoxFormaDePagMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFormaDePagMousePressed
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBoxFormaDePag.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));
            if (totalparcela <= 0) {
                jButtonFinalizar.setEnabled(!true);
            } else {
                jButtonFinalizar.setEnabled(true);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();
    }//GEN-LAST:event_jComboBoxFormaDePagMousePressed

    private void jComboBoxFormaDePagMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFormaDePagMouseReleased
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBoxFormaDePag.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));
            if (totalparcela <= 0) {
                jButtonFinalizar.setEnabled(!true);
            } else {
                jButtonFinalizar.setEnabled(true);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();
    }//GEN-LAST:event_jComboBoxFormaDePagMouseReleased

    private void jComboBoxFormaDePagMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFormaDePagMouseExited
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBoxFormaDePag.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();
    }//GEN-LAST:event_jComboBoxFormaDePagMouseExited

    private void jRadioButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNomeActionPerformed
        flagCliente = 1;
        jRadioButtonCnpj.setSelected(false);
        jTextFieldCliente.setEditable(true);
        try {
            MaskFormatter formcnpj = new MaskFormatter("##.###.###/####-##"); //formato do cnpj
            if (flagCliente == 2) {
                jTextFieldCliente.setFormatterFactory(new DefaultFormatterFactory(formcnpj));
            } else {
                jTextFieldCliente.setText("");
                jTextFieldCliente.setDocument(new CaixaAlta());

            }
        } catch (ParseException ex) {
            Logger.getLogger(ModuloDeVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonNomeActionPerformed

    private void jRadioButtonCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCnpjActionPerformed
        flagCliente = 2;
        jRadioButtonNome.setSelected(false);
        jTextFieldCliente.setEditable(true);
        try {
            MaskFormatter formcnpj = new MaskFormatter("##.###.###/####-##"); //formato do cnpj
            if (flagCliente == 2) {
                jTextFieldCliente.setFormatterFactory(new DefaultFormatterFactory(formcnpj));
            } else {
                jTextFieldCliente.setText("");
                jTextFieldCliente.setDocument(new CaixaAlta());

            }
        } catch (ParseException ex) {
            Logger.getLogger(ModuloDeVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButtonCnpjActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldQtdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            float subtotal;
            int qtdSolicitada = Integer.parseInt(jTextFieldQtdade.getText());
            subtotal = Float.parseFloat(jTextFieldPrecoVenda.getText()) * qtdSolicitada;
            if (testaQuantidade < qtdSolicitada) {
                JOptionPane.showMessageDialog(rootPane, "QUANTIDADE DESEJADA NÃO DISPONÍVEL EM ESTOQUE !");
                jButtonAddProduto.setEnabled(!true);
                jTextFieldPrecoVendaParcial.setText("");
            } else {
                jTextFieldPrecoVendaParcial.setText(String.valueOf(subtotal));
                jButtonAddProduto.setEnabled(true);
            }

        }
    }//GEN-LAST:event_jTextFieldQtdadeKeyPressed

    private void jTextFieldClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteActionPerformed

    private void jLabelProdutoSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelProdutoSelecionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelProdutoSelecionadoActionPerformed

    private void jTextFieldQtdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtdadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Runtime.getRuntime().exec("C:/Windows/System32/calc.exe");
        } catch (Exception ex) {
            System.err.println("ERRO AO CHAMAR CALCULADORA \n" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxFormaDePagFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxFormaDePagFocusLost
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBoxFormaDePag.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();
    }//GEN-LAST:event_jComboBoxFormaDePagFocusLost

    private void jComboBoxFormaDePagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxFormaDePagFocusGained
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBoxFormaDePag.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();
    }//GEN-LAST:event_jComboBoxFormaDePagFocusGained

    private void jComboBoxFormaDePagMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFormaDePagMouseEntered
        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento where nome_forma='" + jComboBoxFormaDePag.getSelectedItem() + "'");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            DecimalFormat fm = new DecimalFormat("0.00");
            jTextFieldParcelasValor.setText(fm.format(totalparcela));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFormaDePagMouseEntered

    private void jTextFieldTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldTotalMouseClicked

    }//GEN-LAST:event_jTextFieldTotalMouseClicked

    private void jTextFieldTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTotalFocusLost

    }//GEN-LAST:event_jTextFieldTotalFocusLost

    private void jTextFieldTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTotalFocusGained

    }//GEN-LAST:event_jTextFieldTotalFocusGained

    public void preencherTabelaPesquisa(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"ID", "Produto", "Referencia", "Preço de Venda", "Quantidade","UND", "Fornecedor"};
        conn.conexao();
        conn.executaSQL(SQL);
        try {
            conn.rs.first();
            do {
                dados.add(new Object[]{conn.rs.getString("id_produto"), conn.rs.getString("nome_produto"), conn.rs.getString("referencia"), conn.rs.getString("preco_venda"), conn.rs.getString("quantidade"),conn.rs.getString("unidade"), conn.rs.getString("nome_fornecedor")});
            } while (conn.rs.next());
        } catch (SQLException ex) {
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        jTablePesquisa1.setModel(modelo);
        jTablePesquisa1.getColumnModel().getColumn(0).setPreferredWidth(110);
        jTablePesquisa1.getColumnModel().getColumn(0).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTablePesquisa1.getColumnModel().getColumn(1).setResizable(true);
        jTablePesquisa1.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTablePesquisa1.getColumnModel().getColumn(2).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTablePesquisa1.getColumnModel().getColumn(3).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTablePesquisa1.getColumnModel().getColumn(4).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTablePesquisa1.getColumnModel().getColumn(5).setResizable(!false);
        jTablePesquisa1.getColumnModel().getColumn(6).setPreferredWidth(600);
        jTablePesquisa1.getColumnModel().getColumn(6).setResizable(!false);

        jTablePesquisa1.getTableHeader().setReorderingAllowed(true);
        jTablePesquisa1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void preencherTabelaVenda(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"ID", "Produto", "Referencia", "Preço de Venda", "Quantidade", "Valor Total"};
        conn.conexao();
        conn.executaSQL(SQL);
        try {
            conn.rs.first();
            do {
                float valorProduto = conn.rs.getFloat("preco_venda");
                int qtdVendida = conn.rs.getInt("quantidade_produto");
                dados.add(new Object[]{conn.rs.getString("id_produto"), conn.rs.getString("nome_produto"), conn.rs.getString("referencia"), conn.rs.getString("preco_venda"), conn.rs.getString("quantidade_produto"), valorProduto * qtdVendida});
            } while (conn.rs.next());
        } catch (SQLException ex) {
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        jTableVenda.setModel(modelo);
        jTableVenda.getColumnModel().getColumn(0).setPreferredWidth(110);
        jTableVenda.getColumnModel().getColumn(0).setResizable(!false);
        jTableVenda.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTableVenda.getColumnModel().getColumn(1).setResizable(true);
        jTableVenda.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTableVenda.getColumnModel().getColumn(2).setResizable(!false);
        jTableVenda.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableVenda.getColumnModel().getColumn(3).setResizable(!false);
        jTableVenda.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTableVenda.getColumnModel().getColumn(4).setResizable(!false);
        jTableVenda.getColumnModel().getColumn(5).setPreferredWidth(600);
        jTableVenda.getColumnModel().getColumn(5).setResizable(!false);

        jTableVenda.getTableHeader().setReorderingAllowed(true);
        jTableVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        somaproduto();
    }

    public void somaproduto() {
        total = 0;

        conn.executaSQL("select * from itens_venda_produto inner join produto on itens_venda_produto.id_produto = produto.id_produto where id_venda ='" + codVenda + "'");
        try {
            while (conn.rs.next()) {
                total = total + (conn.rs.getFloat("preco_venda") * conn.rs.getInt("quantidade_produto"));
                DecimalFormat fm = new DecimalFormat("0.00");
                jTextFieldTotal.setText(fm.format(total));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Somar !" + ex);
        }
        conn.desconecta();
    }

    private void preencherCombobox() {
        conn.conexao();
        conn.executaSQL("select * from forma_pagamento order by id_form_pag");//conecta ao banco de dados
        jComboBoxFormaDePag.removeAllItems();
        try {
            //pega o primeiro dado do banco de dados como parametro
            conn.rs.first();
            do {
                jComboBoxFormaDePag.addItem(conn.rs.getString("nome_forma")); //adiciona os dados ao combobox
            } while (conn.rs.next());//faz o processo anterior enquanto houver proximo.
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox  :" + ex);
        }

        float totalparcela = 0;
        try {
            conn.conexao();
            conn.executaSQL("select * from forma_pagamento orde by id_form_pag");
            conn.rs.first();
            jTextFieldParcelas.setText(conn.rs.getString("fator_pag"));
            totalparcela = (total / Float.parseFloat(jTextFieldParcelas.getText()));
            jTextFieldParcelasValor.setText(String.valueOf(totalparcela));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao setar forma de pagamento para o frame!" + ex);
        }
        conn.desconecta();

    }

    public void chamapedido() {
        conn.conexao();
        buscaRelat = Integer.parseInt(jTextFieldCod.getText());
        try {
            conn.executaSQL("select * from venda\n"
                    + "inner join registro on venda.id_registro = registro.id_registro\n"
                    + "inner join clientes on venda.id_cliente=clientes.id_cliente\n"
                    + "inner join cidade on clientes.id_cidade = cidade.id_cidade\n"
                    + "inner join estados on cidade.id_estado = estados.id_estado\n"
                    + "inner join forma_pagamento on venda.forma=forma_pagamento.nome_forma\n"
                    + "inner join itens_venda_produto on venda.id_venda = itens_venda_produto.id_venda\n"
                    + "inner join produto on produto.id_produto = itens_venda_produto.id_produto\n"
                    + "where itens_venda_produto.id_venda ='" + buscaRelat + "'");

            Map param = new HashMap();
            param.put("BUSCA", buscaRelat);
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conn.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/Pedido.jasper", param, relatResul);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.setExtendedState(MAXIMIZED_BOTH);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO CHAMAR RELATÓRIO  \nErro:" + ex);
        }
        conn.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloDeVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddProduto;
    private javax.swing.JButton jButtonBuscaCliente;
    private javax.swing.JButton jButtonBuscaProduto;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDesconto;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBoxFormaDePag;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLabelProdutoSelecionado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonCnpj;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTablePesquisa1;
    private javax.swing.JTable jTableVenda;
    private javax.swing.JFormattedTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldClienteID;
    private javax.swing.JLabel jTextFieldCod;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldMarkup;
    private javax.swing.JTextField jTextFieldParcelas;
    private javax.swing.JTextField jTextFieldParcelasValor;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldPrecoVendaParcial;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQtdade;
    protected javax.swing.JFormattedTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables

}
