package Visao;

import Controle.Conectabanco;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import Visao.Ultilitarios.SobreOSoftware;
import Visao.Ultilitarios.RelatorioProdutoPorFornecedor;
import java.awt.HeadlessException;
import java.awt.Image;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lucas
 */
public class TelaInicial extends javax.swing.JFrame {

    Conectabanco conecta = new Conectabanco();//variavel global do BD
    String setlaf;

    /**
     * Creates new form TelaPrincipal
     *
     * @param user
     */
    public TelaInicial(String user) {
        initComponents();
        jLabeluser.setText(user);
        //construção do frame de forma de pagamento

        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        conecta.conexao();//chama o metodo de conexão
        //data
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jLabelDatas.setText(df.format(hoje));
        //hora
        Timer timer = new Timer(1000, new hora());
        timer.start();

        conecta.executaSQL("select * from registro");
        try {
            conecta.rs.first();
            jLabelRegistro.setText(conecta.rs.getString("nome"));
            conecta.executaSQL("select * from vencimento");
            try {
                conecta.rs.last();
                char[] datavenc = conecta.rs.getString("data_vencimento").toCharArray();
                jLabelDataVenci.setText("" + datavenc[0] + datavenc[1] + "/" + datavenc[2] + datavenc[3] + "/" + datavenc[4] + datavenc[5] + datavenc[6] + datavenc[7]);
                conecta.desconecta();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERRO DE LICENCIAMENTO \n" + e);
                dispose();
            }
        } catch (SQLException | HeadlessException ex) {
        }
        conecta.desconecta();
    }

    TelaInicial() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelDatas = new javax.swing.JLabel();
        jLabellHoras = new javax.swing.JLabel();
        jLabelRegistro = new javax.swing.JLabel();
        jLabeluser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelDataVenci = new javax.swing.JLabel();
        jLabellHoje = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastromenu = new javax.swing.JMenu();
        clientesmenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        fornecedoresmenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        funcionariosmenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCidades = new javax.swing.JMenuItem();
        jMenuItemEstados = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        consultasmenu = new javax.swing.JMenu();
        materialmenu = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        relatoriosmenu = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        movimentolmenu = new javax.swing.JMenu();
        compramenu = new javax.swing.JMenuItem();
        vendamenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        exitmenui = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemWin = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemNimbus = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyInfo Gestor (Controle de Venda e Estoque)");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/icone.png")).getImage());
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/1 (1578).png"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(1517, 20));

        jLabelDatas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDatas.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelDatas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabellHoras.setBackground(new java.awt.Color(255, 255, 255));
        jLabellHoras.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabellHoras.setForeground(new java.awt.Color(255, 255, 255));
        jLabellHoras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRegistro.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabeluser.setBackground(new java.awt.Color(255, 255, 255));
        jLabeluser.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabeluser.setForeground(new java.awt.Color(255, 255, 255));
        jLabeluser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuário :");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Válido até :");

        jLabelDataVenci.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDataVenci.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelDataVenci.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataVenci.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabellHoje.setBackground(new java.awt.Color(255, 255, 255));
        jLabellHoje.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabellHoje.setForeground(new java.awt.Color(255, 255, 255));
        jLabellHoje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabellHoje.setText("Hoje:");
        jLabellHoje.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabeluser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(153, 153, 153)
                .add(jLabelRegistro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 510, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelDataVenci, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 42, Short.MAX_VALUE)
                .add(jLabellHoje)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelDatas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabellHoras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabellHoras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelDatas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(22, 22, 22))
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabeluser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelRegistro, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabelDataVenci, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jLabellHoje))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel4);

        cadastromenu.setBorder(null);
        cadastromenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/groups-14-128.png"))); // NOI18N
        cadastromenu.setMnemonic('C');
        cadastromenu.setText("Cadastros");
        cadastromenu.setBorderPainted(true);
        cadastromenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastromenu.setInheritsPopupMenu(true);

        clientesmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        clientesmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/SEO_and_Internet_Marketing-39-32.png"))); // NOI18N
        clientesmenu.setText("Clientes");
        clientesmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesmenuActionPerformed(evt);
            }
        });
        cadastromenu.add(clientesmenu);
        cadastromenu.add(jSeparator2);

        fornecedoresmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        fornecedoresmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/2 (23).png"))); // NOI18N
        fornecedoresmenu.setText("Fornecedores");
        fornecedoresmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedoresmenuActionPerformed(evt);
            }
        });
        cadastromenu.add(fornecedoresmenu);
        cadastromenu.add(jSeparator1);

        funcionariosmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        funcionariosmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/2 (26).png"))); // NOI18N
        funcionariosmenu.setText("Usuários");
        funcionariosmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosmenuActionPerformed(evt);
            }
        });
        cadastromenu.add(funcionariosmenu);
        cadastromenu.add(jSeparator3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/2 (24).png"))); // NOI18N
        jMenu2.setText("Outros Cadastros");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/folder_contacts.png"))); // NOI18N
        jMenuItem1.setText("Contatos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator4);

        jMenuItemCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/2 (30).png"))); // NOI18N
        jMenuItemCidades.setText("Cidades");
        jMenuItemCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCidadesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCidades);

        jMenuItemEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/2 (27).png"))); // NOI18N
        jMenuItemEstados.setText("Estados");
        jMenuItemEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemEstados);
        jMenu2.add(jSeparator7);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/forma.png"))); // NOI18N
        jMenuItem5.setText("Formas de Pagamento");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        cadastromenu.add(jMenu2);

        jMenuBar1.add(cadastromenu);

        consultasmenu.setBorder(null);
        consultasmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/36-64.png"))); // NOI18N
        consultasmenu.setMnemonic('O');
        consultasmenu.setText("Consultas");
        consultasmenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        materialmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        materialmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/SEO_and_Internet_Marketing-21-32.png"))); // NOI18N
        materialmenu.setText("Produto");
        materialmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialmenuActionPerformed(evt);
            }
        });
        consultasmenu.add(materialmenu);
        consultasmenu.add(jSeparator9);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/compra.png"))); // NOI18N
        jMenuItem6.setText("Registro de Compras");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        consultasmenu.add(jMenuItem6);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/ven.png"))); // NOI18N
        jMenuItem3.setText("Registro de Vendas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        consultasmenu.add(jMenuItem3);

        jMenuBar1.add(consultasmenu);

        relatoriosmenu.setBorder(null);
        relatoriosmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/144-128.png"))); // NOI18N
        relatoriosmenu.setMnemonic('R');
        relatoriosmenu.setText("Relatórios");
        relatoriosmenu.setToolTipText("");
        relatoriosmenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/Global_Communication-32.png"))); // NOI18N
        jMenuItem7.setText("Clientes Cadastrados");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        relatoriosmenu.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/SEO_and_Internet_Marketing-61-32.png"))); // NOI18N
        jMenuItem8.setText("Fornecedores Cadastrados");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        relatoriosmenu.add(jMenuItem8);
        relatoriosmenu.add(jSeparator10);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/Hand_Truck-32.png"))); // NOI18N
        jMenuItem9.setText("Estoque por Fornecedor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        relatoriosmenu.add(jMenuItem9);

        jMenuBar1.add(relatoriosmenu);

        movimentolmenu.setBorder(null);
        movimentolmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/calculator-64.png"))); // NOI18N
        movimentolmenu.setMnemonic('U');
        movimentolmenu.setText("Movimento");
        movimentolmenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        compramenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        compramenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/1 (15).png"))); // NOI18N
        compramenu.setText("Compra");
        compramenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compramenuActionPerformed(evt);
            }
        });
        movimentolmenu.add(compramenu);

        vendamenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        vendamenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/1 (16).png"))); // NOI18N
        vendamenu.setText("Venda");
        vendamenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendamenuMouseClicked(evt);
            }
        });
        vendamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendamenuActionPerformed(evt);
            }
        });
        movimentolmenu.add(vendamenu);

        jMenuBar1.add(movimentolmenu);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/finan.png"))); // NOI18N
        jMenu3.setText("Financeiro");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/recive.png"))); // NOI18N
        jMenuItem11.setText("Contas à Receber");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);
        jMenu3.add(jSeparator12);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/pay.png"))); // NOI18N
        jMenuItem12.setText("Contas à Pagar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        exitmenui.setBorder(null);
        exitmenui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/option.png"))); // NOI18N
        exitmenui.setText("Opções");
        exitmenui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitmenui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitmenuiMouseClicked(evt);
            }
        });

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/basic1-065_computer_lock_security-32.png"))); // NOI18N
        jMenuItem10.setText("Registro");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        exitmenui.add(jMenuItem10);
        exitmenui.add(jSeparator6);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/SEO_and_Internet_Marketing-76-32.png"))); // NOI18N
        jMenu1.setText("Temas");

        jMenuItemWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/Windows.png"))); // NOI18N
        jMenuItemWin.setText("Windows");
        jMenuItemWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWinActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemWin);
        jMenu1.add(jSeparator5);

        jMenuItemNimbus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/nimbus.png"))); // NOI18N
        jMenuItemNimbus.setText("Nimbus");
        jMenuItemNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNimbusActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNimbus);

        exitmenui.add(jMenu1);
        exitmenui.add(jSeparator8);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/SEO_and_Internet_Marketing-96-32.png"))); // NOI18N
        jMenuItem4.setText("Sobre...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        exitmenui.add(jMenuItem4);
        exitmenui.add(jSeparator11);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Icones metro/power-32.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        exitmenui.add(jMenuItem2);

        jMenuBar1.add(exitmenui);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1291, 833));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clientesmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesmenuActionPerformed
        ConsultaDeClientes frm = new ConsultaDeClientes();
        frm.setVisible(true);
    }//GEN-LAST:event_clientesmenuActionPerformed

    private void funcionariosmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosmenuActionPerformed
        conecta.conexao();
        conecta.executaSQL("select * from login where login ='" + jLabeluser.getText() + "'");
        try {

            conecta.rs.first();
            if (conecta.rs.getString("permissao").equals("Administrador") || (conecta.rs.getString("permissao").equals("Desenvolvedor"))) {
                CadastroDeUsuarios frm = new CadastroDeUsuarios();
                frm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ACESSO NEGADO, USUÁRIO SEM PREMISSÃO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_funcionariosmenuActionPerformed

    private void materialmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialmenuActionPerformed
        ConsultaDeProdutos frm = new ConsultaDeProdutos();
        frm.setVisible(true);
    }//GEN-LAST:event_materialmenuActionPerformed

    private void fornecedoresmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedoresmenuActionPerformed
        ConsultaDeFornecedores frm = new ConsultaDeFornecedores();
        frm.setVisible(true);
    }//GEN-LAST:event_fornecedoresmenuActionPerformed

    private void compramenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compramenuActionPerformed
        ModuloDeCompras frm = new ModuloDeCompras();
        frm.setVisible(true);
    }//GEN-LAST:event_compramenuActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:

    }//GEN-LAST:event_timer1OnTime

    private void exitmenuiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitmenuiMouseClicked

    }//GEN-LAST:event_exitmenuiMouseClicked

    private void jMenuItemEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadosActionPerformed
        // TODO add your handling code here:
        CadastroDeEstados frm = new CadastroDeEstados();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstadosActionPerformed

    private void jMenuItemCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCidadesActionPerformed
        // TODO add your handling code here:
        CadastroDeCidades frm = new CadastroDeCidades();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemCidadesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroDeContatos frm = new CadastroDeContatos();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void vendamenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendamenuMouseClicked

    }//GEN-LAST:event_vendamenuMouseClicked

    private void vendamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendamenuActionPerformed
        ModuloDeVendas frm = new ModuloDeVendas();
        frm.setVisible(true);
    }//GEN-LAST:event_vendamenuActionPerformed

    private void jMenuItemWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWinActionPerformed
        setlaf = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_jMenuItemWinActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        fechasistema();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNimbusActionPerformed
        setlaf = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_jMenuItemNimbusActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ConsultaDeVendas frm = new ConsultaDeVendas();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        SobreOSoftware frm = new SobreOSoftware();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FormasDePagamento frame = new FormasDePagamento();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ConsultaDeCompras frm = new ConsultaDeCompras();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        conecta.conexao();
        try {
            conecta.executaSQL("select * from clientes inner join cidade on clientes.id_cidade=cidade.id_cidade inner join estados on cidade.id_estado=estados.id_estado");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/Clientes.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.setExtendedState(MAXIMIZED_BOTH);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO CHAMAR RELATÓRIO \nErro:" + ex);
        }
        conecta.desconecta();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        conecta.conexao();
        try {
            conecta.executaSQL("select * from fornecedores inner join cidade on fornecedores.id_cidade=cidade.id_cidade inner join estados on cidade.id_estado=estados.id_estado");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/Fornecedores.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.setExtendedState(MAXIMIZED_BOTH);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO CHAMAR RELATÓRIO \nErro:" + ex);
        }
        conecta.desconecta();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        RelatorioProdutoPorFornecedor frm = new RelatorioProdutoPorFornecedor();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        conecta.conexao();
        conecta.executaSQL("select * from login where login ='" + jLabeluser.getText() + "'");
        try {

            conecta.rs.first();
            if (conecta.rs.getString("permissao").equals("Administrador") || (conecta.rs.getString("permissao").equals("Desenvolvedor"))) {
                CadastroDaEmpresa frm = new CadastroDaEmpresa(jLabeluser.getText());
                frm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ACESSO NEGADO, USUÁRIO SEM PREMISSÃO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        conecta.conexao();
        conecta.executaSQL("select * from login where login ='" + jLabeluser.getText() + "'");
        try {

            conecta.rs.first();
            if (conecta.rs.getString("permissao").equals("Administrador") || (conecta.rs.getString("permissao").equals("Desenvolvedor"))) {
                ConsultaContasAReceber frm = new ConsultaContasAReceber();
                frm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ACESSO NEGADO, USUÁRIO SEM PREMISSÃO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        conecta.conexao();
        conecta.executaSQL("select * from login where login ='" + jLabeluser.getText() + "'");
        try {

            conecta.rs.first();
            if (conecta.rs.getString("permissao").equals("Administrador") || (conecta.rs.getString("permissao").equals("Desenvolvedor"))) {
                ConsultaContasAPagar frm = new ConsultaContasAPagar();
                frm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ACESSO NEGADO, USUÁRIO SEM PREMISSÃO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    public void lookandfeel() {
        try {
            UIManager.setLookAndFeel(setlaf);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException erro) {
            JOptionPane.showMessageDialog(null, erro);

        }
    }

    public final void fechasistema() {
        switch (JOptionPane.showConfirmDialog(null, "DESEJA ABANDONAR O SISTEMA ?  ")) {
            case 0:
                conecta.conexao();
                conecta.executaSQL("select count(*) from pg_stat_activity; \n"
                        + "select pid,query,state from pg_stat_activity where state like 'idle';  \n"
                        + "select pg_terminate_backend(pid) from pg_stat_activity where state='idle' and pid <> pg_backend_pid();  \n"
                        + "select pid,query,state from pg_stat_activity where state like 'idle'; ");
                conecta.desconecta();
                System.exit(0);
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
            }

            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cadastromenu;
    private javax.swing.JMenuItem clientesmenu;
    private javax.swing.JMenuItem compramenu;
    private javax.swing.JMenu consultasmenu;
    private javax.swing.JMenu exitmenui;
    private javax.swing.JMenuItem fornecedoresmenu;
    private javax.swing.JMenuItem funcionariosmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDataVenci;
    private javax.swing.JLabel jLabelDatas;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabellHoje;
    private javax.swing.JLabel jLabellHoras;
    private javax.swing.JLabel jLabeluser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemCidades;
    private javax.swing.JMenuItem jMenuItemEstados;
    private javax.swing.JMenuItem jMenuItemNimbus;
    private javax.swing.JMenuItem jMenuItemWin;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem materialmenu;
    private javax.swing.JMenu movimentolmenu;
    private javax.swing.JMenu relatoriosmenu;
    private javax.swing.JMenuItem vendamenu;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            jLabellHoras.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

}
