/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Ultilitarios;

import Controle.Conectabanco;
import Controle.ControleFornecedor;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Modelo.ModeloFornecedor;
import Modelo.ModeloTabela;
import Visao.ModuloDeCompras;

/**
 *
 * @author Administrador
 */
public class BuscaFornecedor extends javax.swing.JFrame {
    Conectabanco connforn = new Conectabanco();
    ModeloFornecedor mod = new ModeloFornecedor();
    ControleFornecedor control = new ControleFornecedor();
    ModuloDeCompras recebe;
    RelatorioProdutoPorFornecedor recebebusca;
    int flagbusca;
    /**
     * Creates new form FrmResultFornecedor
     */
    public BuscaFornecedor() {
    initComponents();

    }
     public void enviaPesquisa(String nomeCli){
        mod.setBusca(nomeCli);
        ModeloFornecedor model = control.buscaCadastro(mod);
        preencherTabelaForn("select * from fornecedores where nome_fornecedor like '%"+ mod.getBusca()+"%'"); 
        flagbusca=1;
    }
     public void enviaPesquisaRelat(String nomeCli){
        mod.setBusca(nomeCli);
        ModeloFornecedor model = control.buscaCadastro(mod);
        preencherTabelaForn("select * from fornecedores where nome_fornecedor like '%"+ mod.getBusca()+"%'"); 
        flagbusca=2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisaForncedor = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldFornecedor = new javax.swing.JTextField();
        jButtonVincular = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/icone.png")).getImage());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Buscar Fornecedor:");

        jTablePesquisaForncedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisaForncedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaForncedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisaForncedor);

        jLabel20.setText("Forncedor Selecionado :");

        jTextFieldFornecedor.setEditable(false);

        jButtonVincular.setText("Vincular");
        jButtonVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVincularActionPerformed(evt);
            }
        });

        jButtonExit.setText("Sair");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFornecedor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVincular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExit))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel19)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVincular)
                    .addComponent(jButtonExit))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePesquisaForncedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaForncedorMouseClicked
        String nome_cliente =""+ jTablePesquisaForncedor.getValueAt(jTablePesquisaForncedor.getSelectedRow(),1);
        connforn.conexao();
        connforn.executaSQL("select * from fornecedores where nome_fornecedor like '"+nome_cliente+"'");

        try {
            connforn.rs.first();
            jTextFieldFornecedor.setText(connforn.rs.getString("nome_fornecedor"));

            connforn.desconecta();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog (null,"Erro ao Carregar da tabela !" +ex);

        }
    }//GEN-LAST:event_jTablePesquisaForncedorMouseClicked

    private void jButtonVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVincularActionPerformed
if (flagbusca<=1){
        recebe = new ModuloDeCompras();
        recebe.recebeDadosFornecedor(jTextFieldFornecedor.getText());
        recebe.setVisible(true);
        connforn.desconecta();
} else{
        recebebusca = new RelatorioProdutoPorFornecedor();
        recebebusca.recebeDadosForn(jTextFieldFornecedor.getText());
        recebebusca.setVisible(true);
        connforn.desconecta();
                    
                    } 
        
        dispose();
    }//GEN-LAST:event_jButtonVincularActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
 if (flagbusca<=1){
        recebe = new ModuloDeCompras();
        recebe.setVisible(true);
        connforn.desconecta();
        dispose();
} else{
       recebebusca = new RelatorioProdutoPorFornecedor();
       recebebusca.setVisible(true);
       connforn.desconecta();
 }
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

   public void preencherTabelaForn(String SQL){
    ArrayList dados = new ArrayList ();
    String [] Colunas = new String[]{"ID","Fornecedor","Inscrição Estadual","CNPJ"};
    connforn.conexao();
    connforn.executaSQL(SQL);
   try {
        connforn.rs.first();
        do{
          dados.add(new Object[]{connforn.rs.getInt("id_fornecedor"), connforn.rs.getString("nome_fornecedor"),connforn.rs.getString("ie_forn"),connforn.rs.getString("cnpj_fornecedor")});
          }while(connforn.rs.next());
        } catch (SQLException ex){
        }
   ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
   jTablePesquisaForncedor.setModel(modelo);
   jTablePesquisaForncedor.getColumnModel().getColumn(0).setPreferredWidth(50);
   jTablePesquisaForncedor.getColumnModel().getColumn(0).setResizable(!false);
   jTablePesquisaForncedor.getColumnModel().getColumn(1).setPreferredWidth(280);
   jTablePesquisaForncedor.getColumnModel().getColumn(1).setResizable(true);
   jTablePesquisaForncedor.getColumnModel().getColumn(2).setPreferredWidth(130);
   jTablePesquisaForncedor.getColumnModel().getColumn(2).setResizable(!false);
   jTablePesquisaForncedor.getColumnModel().getColumn(3).setPreferredWidth(280);
   jTablePesquisaForncedor.getColumnModel().getColumn(3).setResizable(!false);


   jTablePesquisaForncedor.getTableHeader().setReorderingAllowed(true);
   jTablePesquisaForncedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
  
   }
   
    public void enviaPesquisaCNPJ(String CNPJForn) {
      mod.setBusca(CNPJForn);
        ModeloFornecedor model = control.buscaCadastroCNPJ(mod);
        preencherTabelaForn("select * from fornecedores where cnpj_fornecedor like '%"+ mod.getBusca()+"%'"); 
        flagbusca=1;
    }
    
      public void enviaPesquisaCNPJRelat(String CNPJForn) {
      mod.setBusca(CNPJForn);
        ModeloFornecedor model = control.buscaCadastroCNPJ(mod);
        preencherTabelaForn("select * from fornecedores where cnpj_fornecedor like '%"+ mod.getBusca()+"%'"); 
        flagbusca=2;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonVincular;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisaForncedor;
    private javax.swing.JTextField jTextFieldFornecedor;
    // End of variables declaration//GEN-END:variables
}
