/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Ultilitarios;

import Controle.Conectabanco;
import Controle.ControleParcelamentodeTitulos;
import Controle.ModeloTitulos;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Modelo.ModeloTabela;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrador
 */
public class GeraParcelasVenda extends javax.swing.JFrame {
int qtd_parcelas,i=1,cont=1,buscarelat;
Conectabanco conecta = new Conectabanco();
ModeloTitulos mod = new ModeloTitulos();
ControleParcelamentodeTitulos control = new ControleParcelamentodeTitulos();

    /**
     * Creates new form FrmGerarParcelamento
     */
    public GeraParcelasVenda(int cod) {
        initComponents();
        conecta.conexao();
        conecta.executaSQL("select * from venda where id_venda ="+cod);
        try {
            conecta.rs.first();
            jTextFieldIDVenda.setText(String.valueOf(cod));
            jTextFieldValorvenda.setText(conecta.rs.getString("valor_venda"));
            jTextFieldForma.setText(conecta.rs.getString("forma"));
            jTextFieldParcelas.setText(conecta.rs.getString("qtd_parcelas"));
            jTextFieldParcelasValor.setText(conecta.rs.getString("valor_parcela"));
            jTextFieldData.setText(conecta.rs.getString("data_venda"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO VINCULAR VENDA \n!"   +ex);
        }
        
                
    }
    private GeraParcelasVenda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDVenda = new javax.swing.JTextField();
        jTextFieldForma = new javax.swing.JTextField();
        jTextFieldValorvenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldParcelas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldParcelasValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Principal/Imagens/icone.png")).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerador de Títulos (Vendas)", 0, 0, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jLabel1.setText("Movimento (Nº)");

        jTextFieldIDVenda.setEditable(false);
        jTextFieldIDVenda.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldIDVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldForma.setEditable(false);
        jTextFieldForma.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldValorvenda.setEditable(false);

        jLabel2.setText("Valor da Venda:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Forma de Pagamento:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Parcelas :");

        jTextFieldParcelas.setEditable(false);
        jTextFieldParcelas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldParcelas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasFocusLost(evt);
            }
        });

        jLabel13.setText("Valor por Parcela :");

        jTextFieldParcelasValor.setEditable(false);
        jTextFieldParcelasValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldParcelasValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParcelasValorFocusLost(evt);
            }
        });

        jLabel3.setText("Data:");

        jTextFieldData.setEditable(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        jButton1.setText("Parcelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gerar Títulos");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValorvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldForma, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2))
                            .addComponent(jTextFieldIDVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldParcelasValor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)))
                                .addGap(0, 36, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldIDVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldParcelasValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldParcelasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasFocusGained

    private void jTextFieldParcelasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasFocusLost

    private void jTextFieldParcelasValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasValorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasValorFocusGained

    private void jTextFieldParcelasValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParcelasValorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasValorFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        qtd_parcelas =Integer.parseInt(jTextFieldParcelas.getText());
        preencherTabela();
       jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int j=1;
String datavenc = jTextFieldData.getText();
String dia,mes,ano;
dia=""+datavenc.charAt(0)+datavenc.charAt(1)+ "/";
mes=""+datavenc.charAt(3)+datavenc.charAt(4);
ano="/"+datavenc.charAt(6)+datavenc.charAt(7)+datavenc.charAt(8)+datavenc.charAt(9);
int anoInt = Integer.parseInt(""+datavenc.charAt(6)+datavenc.charAt(7)+datavenc.charAt(8)+datavenc.charAt(9));
int mesInt= Integer.parseInt(mes)+1;
while(j<cont){
       if (mesInt<10){
    mod.setCodVenda(Integer.parseInt(jTextFieldIDVenda.getText()));
    mod.setValorparcela(jTextFieldParcelasValor.getText());
    mod.setTotalvenda(jTextFieldValorvenda.getText());
    mod.setNumero_parcela(j);
    mod.setData_parcela(dia+"0"+mesInt+"/"+anoInt);
    mod.setForma(jTextFieldForma.getText());
    
    control.Inserir(mod);       
           
           
       }else{
    mod.setCodVenda(Integer.parseInt(jTextFieldIDVenda.getText()));
    mod.setValorparcela(jTextFieldParcelasValor.getText());
    mod.setTotalvenda(jTextFieldValorvenda.getText());
    mod.setNumero_parcela(j);
    mod.setData_parcela(dia+mesInt+"/"+anoInt);
    control.Inserir(mod);       
       }
        mesInt++;
        if (mesInt>12){
            anoInt++;
            mesInt=1;
        }            
             j++;
       
          }
        
JOptionPane.showMessageDialog(rootPane, "PARCELAS GERADAS !");
chamapedido();
conecta.desconecta();
dispose();
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void preencherTabela(){
    ArrayList dados = new ArrayList ();
    
    String [] Colunas = new String[]{"COD.","Vencimento","Total da Venda","Valor Parcelado",};
    String data = jTextFieldData.getText();
    String dia,mes,ano;
    dia=""+data.charAt(0)+data.charAt(1)+ "/";
    mes=""+data.charAt(3)+data.charAt(4);
    ano="/"+data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9);
    int anoInt = Integer.parseInt(""+data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9));
    int mesInt= Integer.parseInt(mes)+1;
 while(i<=qtd_parcelas){
       if (mesInt<10){
     dados.add(new Object[]{i,dia+"0"+mesInt+"/"+anoInt,jTextFieldValorvenda.getText(),jTextFieldParcelasValor.getText()});
       }else{
           dados.add(new Object[]{i,dia+mesInt+"/"+anoInt,jTextFieldValorvenda.getText(),jTextFieldParcelasValor.getText()});
       }
        mesInt++;
        if (mesInt>12){
            anoInt++;
            mesInt=1;
        }            
             i++;
             cont++;
       
          }
       
   ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
   tabela.setModel(modelo);
   tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
   tabela.getColumnModel().getColumn(0).setResizable(!false);
   tabela.getColumnModel().getColumn(1).setPreferredWidth(80);
   tabela.getColumnModel().getColumn(1).setResizable(true);
   tabela.getColumnModel().getColumn(2).setPreferredWidth(200);
   tabela.getColumnModel().getColumn(2).setResizable(false);
   tabela.getColumnModel().getColumn(3).setPreferredWidth(200);
   tabela.getColumnModel().getColumn(3).setResizable(false);
 
   tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
   tabela.getTableHeader().setReorderingAllowed(true);
   tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
   conecta.desconecta();
   }
    
    
    
    public void chamapedido(){
               conecta.conexao();
  buscarelat = Integer.parseInt(jTextFieldIDVenda.getText());
  try{conecta.executaSQL("select * from venda\n" +
"inner join registro on venda.id_registro = registro.id_registro\n" +
"inner join clientes on venda.id_cliente=clientes.id_cliente\n" +
"inner join cidade on clientes.id_cidade = cidade.id_cidade\n" +
"inner join estados on cidade.id_estado = estados.id_estado\n" +
"inner join forma_pagamento on venda.forma=forma_pagamento.nome_forma\n" +
"inner join itens_venda_produto on venda.id_venda = itens_venda_produto.id_venda\n" +
"inner join produto on produto.id_produto = itens_venda_produto.id_produto\n" +
"where itens_venda_produto.id_venda ='"+buscarelat+"'");
        
    Map param = new HashMap(); 
    param.put("BUSCA", buscarelat);             
    JRResultSetDataSource relatResul = new JRResultSetDataSource (conecta.rs);
    JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/Pedido.jasper",param,relatResul);
          JasperViewer jv = new JasperViewer (jpPrint,false); 
         jv.setVisible(true);
         jv.setExtendedState(MAXIMIZED_BOTH);
        
  }catch(JRException ex)         {
    JOptionPane.showMessageDialog(rootPane, "ERRO AO CHAMAR RELATÓRIO  \nErro:" +ex);
  }
  conecta.desconecta();
    }
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeraParcelasVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeraParcelasVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeraParcelasVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeraParcelasVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeraParcelasVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldForma;
    private javax.swing.JTextField jTextFieldIDVenda;
    private javax.swing.JTextField jTextFieldParcelas;
    private javax.swing.JTextField jTextFieldParcelasValor;
    private javax.swing.JTextField jTextFieldValorvenda;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
